import { Card } from './ui/card';
import { Badge } from './ui/badge';
import { Clock, BookOpen, AlertTriangle } from 'lucide-react';
import { ImageWithFallback } from './figma/ImageWithFallback';
import { AnimatedBackground } from './AnimatedBackground';

interface ArticleDetailProps {
  articleId: string;
}

const articleContent: Record<string, any> = {
  '1': {
    title: 'Cómo Prevenir el Golpe de Calor',
    category: 'Prevención',
    readTime: '8 min',
    categoryColor: 'bg-blue-100 text-blue-700 border-blue-300',
    image: 'https://images.unsplash.com/photo-1673132611640-c5cab8ac3600?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHxkb2clMjBoZWF0c3Ryb2tlJTIwaG90JTIwc3VtbWVyfGVufDF8fHx8MTc2MjAzMDM2MHww&ixlib=rb-4.1.0&q=80&w=1080',
    sections: [
      {
        title: '¿Qué es el Golpe de Calor?',
        content: [
          'El golpe de calor es una emergencia médica que ocurre cuando la temperatura corporal de tu mascota supera los 40°C y su cuerpo no puede enfriarse eficientemente.',
          '',
          'Los perros y gatos NO sudan como los humanos. Solo pueden regular su temperatura mediante:',
          '• Jadeo',
          '• Sudoración mínima en almohadillas',
          '• Vasodilatación periférica',
          '',
          'Esto hace que sean mucho más vulnerables al calor extremo.',
        ],
      },
      {
        title: 'Factores de Riesgo',
        content: [
          'Razas braquicéfalas (alto riesgo):',
          '• Bulldogs (inglés, francés)',
          '• Pugs',
          '• Boston Terrier',
          '• Pequinés',
          '• Persas y Exóticos (gatos)',
          '',
          'Otros factores de riesgo:',
          '• Obesidad',
          '• Edad avanzada o cachorros',
          '• Pelaje muy denso',
          '• Enfermedades cardíacas o respiratorias',
          '• Ejercicio intenso en clima cálido',
          '• Exposición al sol sin sombra',
          '• Quedarse en vehículo cerrado',
        ],
      },
      {
        title: 'Signos de Alerta',
        content: [
          'Signos tempranos (actúa inmediatamente):',
          '• Jadeo excesivo y rápido',
          '• Salivación abundante',
          '• Encías rojas brillantes',
          '• Inquietud o ansiedad',
          '',
          'Signos avanzados (EMERGENCIA):',
          '• Lengua o encías azuladas/moradas',
          '• Vómito',
          '• Diarrea (puede tener sangre)',
          '• Debilidad o colapso',
          '• Convulsiones',
          '• Pérdida de conciencia',
          '',
          'Si observas signos avanzados, enfría mientras te diriges AL VETERINARIO URGENTE.',
        ],
      },
      {
        title: 'Prevención Efectiva',
        content: [
          'En días calurosos (más de 25°C):',
          '',
          '1. NUNCA dejes a tu mascota en el auto:',
          '• Incluso con ventanas abiertas',
          '• La temperatura interior puede alcanzar 50°C en 10 minutos',
          '• Puede ser mortal en menos de 15 minutos',
          '',
          '2. Limita el ejercicio:',
          '• Pasea temprano en la mañana o tarde en la noche',
          '• Evita el asfalto caliente (quema almohadillas)',
          '• Reduce intensidad y duración',
          '',
          '3. Proporciona sombra y agua:',
          '• Acceso constante a agua fresca',
          '• Múltiples fuentes de agua',
          '• Áreas con sombra abundante',
          '• Considera piscinas para perros',
          '',
          '4. Enfriamiento adicional:',
          '• Alfombrillas de enfriamiento',
          '• Ventiladores',
          '• Aire acondicionado en casa',
          '• Juguetes congelados',
          '',
          '5. Reconoce las limitaciones de tu mascota:',
          '• Razas braquicéfalas: extremo cuidado',
          '• Mascotas obesas o ancianas: supervisión cercana',
          '• Perros de trabajo: descansos frecuentes',
        ],
      },
      {
        title: 'Primeros Auxilios para Golpe de Calor',
        content: [
          'Si sospechas golpe de calor, actúa INMEDIATAMENTE:',
          '',
          '1. Mueve a la sombra o lugar fresco',
          '',
          '2. Comienza enfriamiento gradual:',
          '• Usa agua FRESCA (NO helada)',
          '• Moja con toallas o rocía con agua',
          '• Enfoca en cuello, axilas, ingle',
          '• Coloca frente a ventilador',
          '',
          '3. NO uses hielo o agua muy fría:',
          '• Puede causar shock',
          '• Constricción de vasos sanguíneos',
          '• Dificulta el enfriamiento interno',
          '',
          '4. Ofrece agua (si está consciente):',
          '• Pequeños sorbos',
          '• No fuerces',
          '',
          '5. Monitorea temperatura si es posible:',
          '• Objetivo: bajar a 39.5°C',
          '• Luego DETÉN enfriamiento activo',
          '',
          '6. LLEVA AL VETERINARIO:',
          '• Incluso si parece recuperarse',
          '• Complicaciones pueden aparecer horas después',
          '• Puede necesitar fluidos IV y monitoreo',
        ],
      },
    ],
  },
  '2': {
    title: 'Identificación de Alimentos Tóxicos',
    category: 'Seguridad',
    readTime: '12 min',
    categoryColor: 'bg-orange-100 text-orange-700 border-orange-300',
    image: 'https://images.unsplash.com/photo-1617694075888-5600278d27a4?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHx0b3hpYyUyMGZvb2RzJTIwcGV0cyUyMGNob2NvbGF0ZXxlbnwxfHx8fDE3NjIwMzA1NTd8MA&ixlib=rb-4.1.0&q=80&w=1080',
    sections: [
      {
        title: 'Alimentos Comunes Altamente Tóxicos',
        content: [
          'CHOCOLATE:',
          'Contiene teobromina, tóxica para perros y gatos.',
          '',
          'Niveles de toxicidad (de menor a mayor):',
          '• Chocolate blanco: bajo',
          '• Chocolate con leche: moderado',
          '• Chocolate semi-amargo: alto',
          '• Chocolate para cocinar: MUY ALTO',
          '• Cacao en polvo: EXTREMO',
          '',
          'Dosis tóxica: tan poco como 20mg/kg puede causar síntomas',
          'Dosis letal: 100-200mg/kg',
          '',
          'Signos (2-4 horas post-ingestión):',
          '• Vómito y diarrea',
          '• Hiperactividad',
          '• Temblores musculares',
          '• Ritmo cardíaco acelerado',
          '• Convulsiones',
          '',
          'Acción: contacta veterinario INMEDIATAMENTE.',
        ],
      },
      {
        title: 'Xilitol - Peligro Extremo',
        content: [
          'XILITOL (edulcorante artificial):',
          'Extremadamente tóxico para perros, incluso en cantidades mínimas.',
          '',
          'Presente en:',
          '• Chicles y caramelos sin azúcar',
          '• Mantequilla de maní "light" o sin azúcar',
          '• Productos horneados sin azúcar',
          '• Pastas dentales',
          '• Algunos medicamentos',
          '• Vitaminas masticables',
          '',
          'Efectos en perros:',
          '',
          'Fase 1 (15-30 minutos):',
          '• Libera INSULINA masiva',
          '• Hipoglucemia severa',
          '• Debilidad, tambaleo',
          '• Convulsiones',
          '• Colapso',
          '',
          'Fase 2 (12-24 horas):',
          '• Fallo hepático agudo',
          '• Ictericia',
          '• Coagulopatía',
          '',
          'Dosis tóxica: tan poco como 0.1g/kg',
          '',
          'URGENCIA EXTREMA: minutos cuentan. Veterinario INMEDIATO.',
        ],
      },
      {
        title: 'Uvas y Pasas',
        content: [
          'UVAS Y PASAS:',
          'Causan fallo renal agudo en perros. La causa exacta es desconocida.',
          '',
          'Datos importantes:',
          '• Todas las variedades son tóxicas',
          '• Uvas frescas, pasas, sultanas',
          '• NO hay dosis segura conocida',
          '• Algunos perros muy sensibles, otros tolerantes',
          '• Imposible predecir quién será afectado',
          '',
          'Signos (6-12 horas):',
          '• Vómito (temprano)',
          '• Diarrea',
          '• Pérdida de apetito',
          '• Letargo',
          '• Dolor abdominal',
          '',
          'Signos de fallo renal (24-72 horas):',
          '• Disminución o ausencia de orina',
          '• Aliento con olor a amoníaco',
          '• Vómito severo',
          '• Debilidad extrema',
          '',
          'Acción:',
          'Contacta veterinario inmediatamente, incluso si solo sospechas ingestión.',
          'El tratamiento temprano (primeras 2 horas) mejora significativamente el pronóstico.',
        ],
      },
      {
        title: 'Cebolla, Ajo y Familia Allium',
        content: [
          'CEBOLLA, AJO, PUERROS, CEBOLLÍN:',
          'Contienen tiosulfatos que dañan los glóbulos rojos.',
          '',
          'Toxicidad:',
          '• Todas las formas: crudo, cocido, deshidratado, en polvo',
          '• La cebolla es la más tóxica',
          '• El ajo es menos tóxico pero aún peligroso',
          '• Efecto acumulativo',
          '',
          'Cantidad peligrosa:',
          '• Perros: 15-30 g/kg (puede ser una cebolla mediana para un perro pequeño)',
          '• Gatos: mucho más sensibles',
          '',
          'Signos (pueden tardar días):',
          '• Debilidad',
          '• Encías pálidas o amarillentas',
          '• Orina rojo-marrón',
          '• Vómito y diarrea',
          '• Ritmo cardíaco elevado',
          '• Respiración rápida',
          '',
          'Complicación: anemia hemolítica',
          'Puede requerir transfusión sanguínea en casos graves.',
        ],
      },
      {
        title: 'Otros Alimentos Peligrosos',
        content: [
          'AGUACATE:',
          '• Contiene persina',
          '• Tóxico para aves, roedores',
          '• Puede causar vómito/diarrea en perros y gatos',
          '• El hueso puede causar obstrucción',
          '',
          'NUECES DE MACADAMIA:',
          '• Tóxicas para perros',
          '• Causan debilidad en extremidades traseras',
          '• Vómito, temblores, hipertermia',
          '• Dosis tóxica: 2.4 g/kg',
          '',
          'MASA DE LEVADURA:',
          '• Fermenta en estómago',
          '• Produce alcohol (intoxicación)',
          '• Se expande (distensión gástrica)',
          '• Puede causar torsión gástrica',
          '',
          'ALCOHOL:',
          '• Extremadamente peligroso',
          '• Pequeñas cantidades pueden ser mortales',
          '• Afecta sistema nervioso central',
          '• Causa depresión respiratoria',
          '',
          'CAFEÍNA:',
          '• Presente en café, té, bebidas energéticas',
          '• Similar al chocolate (metilxantinas)',
          '• Hiperactividad, taquicardia, convulsiones',
          '',
          'SAL EN EXCESO:',
          '• Causa envenenamiento por sodio',
          '• Vómito, diarrea, convulsiones',
          '• Presente en: snacks salados, masa de modelar',
        ],
      },
      {
        title: 'Qué Hacer si tu Mascota Come Algo Tóxico',
        content: [
          'PASOS INMEDIATOS:',
          '',
          '1. IDENTIFICA qué comió y cuánto',
          '• Guarda el envase o restos',
          '• Calcula la cantidad aproximada',
          '• Anota la hora de ingestión',
          '',
          '2. LLAMA al veterinario o toxicología:',
          '• Describe exactamente qué sucedió',
          '• Peso de tu mascota',
          '• Cantidad ingerida',
          '• Tiempo transcurrido',
          '',
          '3. NO induzcas vómito sin instrucción:',
          '• Puede ser contraproducente para algunas sustancias',
          '• Peligroso si han pasado más de 2 horas',
          '',
          '4. SI te indican inducir vómito en PERROS:',
          '• Peróxido de hidrógeno 3%',
          '• Dosis: 1 ml por kg de peso',
          '• Máximo 45 ml',
          '• Funciona en 10-15 minutos',
          '',
          '5. NUNCA induzcas vómito en gatos en casa',
          '',
          '6. Dirígete al veterinario:',
          '• Lleva muestras del alimento',
          '• Lleva el vómito si ocurrió',
          '',
          'IMPORTANTE:',
          'Mientras más rápido actúes, mejor el pronóstico.',
          'Las primeras 1-2 horas son críticas.',
        ],
      },
    ],
  },
  '3': {
    title: 'Señales de Dolor en Mascotas',
    category: 'Cuidados Básicos',
    readTime: '10 min',
    categoryColor: 'bg-emerald-100 text-emerald-700 border-emerald-300',
    image: 'https://images.unsplash.com/photo-1707764075738-d3689b15764d?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHxkb2clMjBwYWluJTIwYmVoYXZpb3J8ZW58MXx8fHwxNzYyMDMwNTU3fDA&ixlib=rb-4.1.0&q=80&w=1080',
    sections: [
      {
        title: 'Por Qué las Mascotas Ocultan el Dolor',
        content: [
          'Los animales instintivamente ocultan signos de dolor o debilidad:',
          '',
          'Razones evolutivas:',
          '• En la naturaleza, mostrar debilidad atrae predadores',
          '• Los animales enfermos son excluidos de la manada',
          '• Instinto de supervivencia arraigado',
          '',
          'Esto significa:',
          '• Para cuando notes el dolor, puede ser severo',
          '• Los signos sutiles son importantes',
          '• Debes conocer muy bien el comportamiento normal de tu mascota',
          '• Los cambios pequeños pueden indicar problemas grandes',
        ],
      },
      {
        title: 'Signos de Dolor en Perros',
        content: [
          'Cambios de comportamiento:',
          '• Menos activo o reacio a moverse',
          '• No quiere subir escaleras o saltar',
          '• Se aleja o esconde',
          '• Agresión inusual (gruñe cuando lo tocas)',
          '• Menos interacción social',
          '• Cambios en el sueño',
          '',
          'Signos físicos:',
          '• Cojera o caminar rígido',
          '• Postura encorvada',
          '• Respiración rápida o superficial',
          '• Temblores',
          '• Inquietud, no puede ponerse cómodo',
          '',
          'Expresión facial:',
          '• Ojos entrecerrados o vidriosos',
          '• Orejas hacia atrás',
          '• Ceño fruncido',
          '• Mirada ausente o fija',
          '',
          'Vocalización:',
          '• Quejidos, gemidos',
          '• Ladridos cuando lo tocas',
          '• Jadeo excesivo',
          '',
          'Cambios de apetito:',
          '• Come menos o nada',
          '• Dificultad para masticar',
          '• Prefiere comida blanda',
        ],
      },
      {
        title: 'Signos de Dolor en Gatos',
        content: [
          'Los gatos son especialmente buenos ocultando dolor:',
          '',
          'Cambios de comportamiento:',
          '• Menos acicalamiento (pelaje descuidado)',
          '• Acicalamiento excesivo en un área',
          '• Evita saltar a lugares altos',
          '• Se esconde más',
          '• Menos juego',
          '• Cambios en rutina de sueño',
          '',
          'Expresión facial felina del dolor:',
          '• Orejas aplanadas hacia los lados',
          '• Ojos entrecerrados',
          '• Bigotes hacia adelante y tensos',
          '• Hocico tenso',
          '• Cabeza por debajo del nivel de hombros',
          '',
          'Postura:',
          '• Posición "en bola" cerrada',
          '• Cabeza presionada contra superficies',
          '• Reacio a moverse',
          '• Postura rígida al sentarse',
          '',
          'Uso de la caja de arena:',
          '• Evita la caja (dolor al agacharse)',
          '• Elimina fuera de la caja',
          '• Entra y sale rápidamente',
          '',
          'Vocalización:',
          '• Maullidos inusuales',
          '• Gruñidos o siseos',
          '• Ronroneo (puede indicar dolor, no siempre felicidad)',
        ],
      },
      {
        title: 'Dolor Agudo vs Crónico',
        content: [
          'DOLOR AGUDO:',
          'Aparición súbita, intenso.',
          '',
          'Causas comunes:',
          '• Lesiones traumáticas',
          '• Heridas',
          '• Cirugía reciente',
          '• Infecciones agudas',
          '• Obstrucción intestinal',
          '',
          'Signos:',
          '• Cambio repentino de comportamiento',
          '• Vocalización',
          '• No quiere que lo toquen',
          '• Respiración rápida',
          '• Postura anormal',
          '',
          'Acción: busca atención veterinaria inmediata',
          '',
          'DOLOR CRÓNICO:',
          'Desarrolla gradualmente, persistente.',
          '',
          'Causas comunes:',
          '• Artritis',
          '• Enfermedad dental',
          '• Cáncer',
          '• Enfermedades de órganos',
          '',
          'Signos:',
          '• Cambios sutiles en semanas/meses',
          '• Disminución gradual de actividad',
          '• Cambios de personalidad',
          '• Pérdida de peso',
          '',
          'Acción: programa evaluación veterinaria',
        ],
      },
      {
        title: 'Evaluación del Dolor en Casa',
        content: [
          'Observa estos aspectos de tu mascota:',
          '',
          '1. MOVILIDAD:',
          '• ¿Salta con normalidad?',
          '• ¿Usa escaleras sin problemas?',
          '• ¿Camina sin cojear?',
          '• ¿Juega como siempre?',
          '',
          '2. APETITO:',
          '• ¿Come con entusiasmo normal?',
          '• ¿Mastica sin problemas?',
          '• ¿Ha cambiado preferencias de comida?',
          '',
          '3. INTERACCIÓN:',
          '• ¿Busca atención como antes?',
          '• ¿Responde a llamados?',
          '• ¿Evita ser tocado?',
          '',
          '4. HIGIENE:',
          '• Perros: ¿Se acicala normalmente?',
          '• Gatos: ¿Pelaje brillante y limpio?',
          '',
          '5. DESCANSO:',
          '• ¿Duerme en posiciones normales?',
          '• ¿Parece cómodo?',
          '• ¿Se levanta fácilmente?',
          '',
          'Test de palpación gentil:',
          '• Con cuidado, toca diferentes áreas',
          '• Observa reacciones',
          '• Compara lados del cuerpo',
          '• DETÉN si muestra incomodidad',
        ],
      },
      {
        title: 'Cuándo Buscar Ayuda',
        content: [
          'Busca atención veterinaria URGENTE si:',
          '',
          '• Vocalización constante de dolor',
          '• No puede levantarse o caminar',
          '• Respiración muy rápida o dificultosa',
          '• Abdomen tenso y doloroso',
          '• No come ni bebe por más de 24 horas',
          '• Vómito o diarrea con signos de dolor',
          '• Trauma reciente (accidente, caída)',
          '• Sangrado',
          '• Hinchazón repentina',
          '',
          'Programa cita veterinaria si:',
          '',
          '• Cojera persistente (más de 24 horas)',
          '• Disminución gradual de actividad',
          '• Cambios de comportamiento sutiles pero persistentes',
          '• Menor interés en actividades favoritas',
          '• Cambios en apetito',
          '• Mascotas mayores (evaluaciones regulares)',
          '',
          'NO AUTOMEDIQUES:',
          '• Ibuprofeno, aspirina, paracetamol son TÓXICOS',
          '• Medicamentos humanos pueden ser mortales',
          '• Solo da medicamentos prescritos por veterinario',
        ],
      },
    ],
  },
  '4': {
    title: 'Preparación para Emergencias',
    category: 'Prevención',
    readTime: '15 min',
    categoryColor: 'bg-blue-100 text-blue-700 border-blue-300',
    image: 'https://images.unsplash.com/photo-1642513730687-13d52167b978?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHxwZXQlMjBlbWVyZ2VuY3klMjBwcmVwYXJhdGlvbnxlbnwxfHx8fDE3NjIwMzA1NTh8MA&ixlib=rb-4.1.0&q=80&w=1080',
    sections: [
      {
        title: 'Kit de Emergencias para Mascotas',
        content: [
          'Todo dueño de mascota debe tener un kit de primeros auxilios listo:',
          '',
          'SUMINISTROS BÁSICOS:',
          '• Gasa estéril (rollos y cuadrados)',
          '• Vendas cohesivas (no adhesivas)',
          '• Cinta adhesiva médica',
          '• Tijeras de punta roma',
          '• Pinzas',
          '• Termómetro digital rectal',
          '• Lubricante (para termómetro)',
          '• Guantes desechables',
          '• Toallas limpias',
          '• Mantas',
          '',
          'MEDICAMENTOS Y SOLUCIONES:',
          '• Solución salina estéril',
          '• Clorhexidina diluida (antiséptico)',
          '• Pomada antibiótica (sin corticoides)',
          '• Peróxido de hidrógeno 3% (para inducir vómito en perros)',
          '• Carbón activado (si lo recomienda veterinario)',
          '',
          'HERRAMIENTAS:',
          '• Linterna',
          '• Bozal o gasa (para seguridad)',
          '• Jeringa sin aguja (dar medicamentos orales)',
          '• Gotero',
          '',
          'INFORMACIÓN:',
          '• Números de emergencia veterinaria',
          '• Registro de vacunación',
          '• Historial médico',
          '• Foto reciente de tu mascota',
          '• Contactos de emergencia',
        ],
      },
      {
        title: 'Números de Emergencia Esenciales',
        content: [
          'Ten estos números fácilmente accesibles:',
          '',
          '1. Veterinario habitual',
          '• Horario regular',
          '• Número directo',
          '',
          '2. Clínica de emergencias 24/7',
          '• Hospital veterinario más cercano',
          '• Conoce la ubicación exacta',
          '• Ten alternativas',
          '',
          '3. Centro de toxicología veterinaria',
          '• Disponible 24/7',
          '• Información sobre envenenamientos',
          '',
          '4. Veterinario de respaldo',
          '• Si el tuyo no está disponible',
          '',
          '5. Transporte de emergencia',
          '• Si no puedes transportar tú mismo',
          '',
          'CREA UNA TARJETA DE EMERGENCIA:',
          '• Todos los números en un lugar',
          '• En tu billetera',
          '• En el refrigerador',
          '• Programados en tu teléfono',
          '• Compartidos con cuidadores',
        ],
      },
      {
        title: 'Plan de Evacuación para Mascotas',
        content: [
          'En caso de desastre natural o emergencia local:',
          '',
          'PREPARACIÓN PREVIA:',
          '',
          '1. Kit de evacuación (separado de kit de primeros auxilios):',
          '• Comida para 7 días',
          '• Agua embotellada (1 litro por día)',
          '• Medicamentos para 2 semanas',
          '• Platos plegables',
          '• Correa extra, collar con ID',
          '• Transportadora o jaula',
          '• Arena para gatos / bolsas para desechos',
          '• Juguetes favoritos / mantas',
          '• Documentos importantes en bolsa sellada',
          '',
          '2. Identificación:',
          '• Microchip actualizado',
          '• Collar con placa ID',
          '• Foto reciente clara',
          '',
          '3. Ubicaciones seguras pre-identificadas:',
          '• Hoteles pet-friendly fuera de tu área',
          '• Familiares / amigos que acepten mascotas',
          '• Refugios para animales en emergencias',
          '',
          'DURANTE EVACUACIÓN:',
          '',
          '• NUNCA dejes tu mascota atrás',
          '• Lleva el kit de evacuación',
          '• Mantén a los perros con correa, gatos en transportadora',
          '• Ten documentos a mano (vacunación)',
          '• Lleva foto reciente por si se pierde',
        ],
      },
      {
        title: 'Preparación para Emergencias Médicas',
        content: [
          'Cómo estar preparado para emergencias de salud:',
          '',
          '1. CONOCE LAS CONSTANTES NORMALES:',
          'Toma medidas cuando tu mascota está sana:',
          '',
          '• Temperatura normal',
          '• Frecuencia cardíaca en reposo',
          '• Frecuencia respiratoria en reposo',
          '• Color de encías',
          '• Tiempo de llenado capilar',
          '',
          'Practica tomarlas regularmente.',
          '',
          '2. APRENDE TÉCNICAS BÁSICAS:',
          '• Cómo tomar temperatura rectal',
          '• Dónde encontrar pulso',
          '• Cómo revisar mucosas',
          '• Técnica de test de deshidratación',
          '• Posiciones de transporte seguro',
          '',
          '3. IDENTIFICA VETERINARIOS DE EMERGENCIA:',
          '• Visita antes de necesitarlos',
          '• Conoce la ruta más rápida',
          '• Ten alternativas',
          '• Conoce sus políticas de pago',
          '',
          '4. CONSIDERA SEGURO PARA MASCOTAS:',
          '• Cubre emergencias inesperadas',
          '• Reduce estrés financiero',
          '• Permite mejores decisiones médicas',
        ],
      },
      {
        title: 'Seguridad en el Hogar',
        content: [
          'Prevén emergencias haciendo tu hogar seguro:',
          '',
          'COCINA:',
          '• Guarda basura en recipiente con tapa',
          '• Almacena alimentos tóxicos fuera de alcance',
          '• No dejes comida en bordes de encimera',
          '• Cuidado con cables de electrodomésticos',
          '',
          'BAÑO:',
          '• Medicamentos en gabinetes cerrados',
          '• Productos de limpieza guardados',
          '• Tapa del inodoro cerrada',
          '',
          'GARAJE/ÁREA DE ALMACENAMIENTO:',
          '• Anticongelante guardado seguro',
          '• Raticidas inaccesibles',
          '• Herramientas guardadas',
          '• Químicos en gabinetes con llave',
          '',
          'JARDÍN:',
          '• Identifica plantas tóxicas',
          '• Almacena fertilizantes/pesticidas seguros',
          '• Asegura piscinas',
          '• Revisa cercas regularmente',
          '',
          'GENERAL:',
          '• Cables eléctricos protegidos',
          '• Objetos pequeños fuera de alcance',
          '• Bolsas plásticas guardadas',
          '• Ventanas aseguradas (gatos)',
          '',
          'INSPECCIÓN REGULAR:',
          'Haz un recorrido mensual buscando peligros potenciales.',
        ],
      },
    ],
  },
  '5': {
    title: 'Plantas Tóxicas Comunes en el Hogar',
    category: 'Seguridad',
    readTime: '10 min',
    categoryColor: 'bg-orange-100 text-orange-700 border-orange-300',
    image: 'https://images.unsplash.com/photo-1660294767665-0793f7866eeb?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHx0b3hpYyUyMGhvdXNlcGxhbnRzfGVufDF8fHx8MTc2MjAzMTg1MHww&ixlib=rb-4.1.0&q=80&w=1080',
    sections: [
      {
        title: 'Plantas de Interior Peligrosas',
        content: [
          'Muchas plantas decorativas comunes son tóxicas para mascotas. La gravedad varía desde irritación leve hasta fallo orgánico mortal.',
          '',
          'LIRIOS (Lilium spp., Hemerocallis spp.):',
          'EXTREMADAMENTE TÓXICOS para gatos, incluso en pequeñas cantidades.',
          '',
          'Todas las partes son venenosas:',
          '• Flores, pétalos',
          '• Hojas y tallos',
          '• Polen',
          '• Agua del florero',
          '',
          'Efectos en gatos:',
          '• Fallo renal agudo (12-24 horas)',
          '• Vómito',
          '• Letargo',
          '• Pérdida de apetito',
          '• Sin tratamiento: mortal en 3-7 días',
          '',
          'URGENCIA: Contacta veterinario INMEDIATAMENTE si sospechas exposición.',
          'El tratamiento temprano (primeras 6 horas) puede salvar la vida.',
          '',
          'Nota: Los lirios son relativamente seguros para perros, pero evítalos de todas formas.',
        ],
      },
      {
        title: 'Plantas Populares con Toxicidad Moderada',
        content: [
          'POTHOS/POTOS (Epipremnum aureum):',
          'Planta colgante muy popular, tóxica para perros y gatos.',
          '',
          'Toxina: Oxalato de calcio insoluble',
          '',
          'Síntomas:',
          '• Irritación oral inmediata',
          '• Babeo excesivo',
          '• Dificultad para tragar',
          '• Vómito',
          '• Hinchazón de boca y lengua',
          '',
          'Tratamiento: generalmente sintomático, rara vez mortal',
          '',
          'FILODENDRO (Philodendron spp.):',
          'Similar al pothos en toxicidad y síntomas.',
          '',
          'ESPATIFILO/CUNA DE MOISÉS (Spathiphyllum):',
          'También contiene oxalatos de calcio.',
          '',
          'Síntomas similares:',
          '• Irritación oral',
          '• Babeo',
          '• Dificultad para tragar',
          '',
          'DIFENBAQUIA/DIEFFENBACHIA:',
          'Conocida como "caña muda".',
          '',
          'Altamente irritante:',
          '• Hinchazón severa de lengua',
          '• Puede causar dificultad respiratoria',
          '• Babeo profuso',
          '• En casos graves: bloqueo de vías respiratorias',
        ],
      },
      {
        title: 'Plantas Suculentas y Tropicales',
        content: [
          'ALOE VERA:',
          'Aunque tiene usos medicinales humanos, es tóxica para mascotas.',
          '',
          'Síntomas en perros y gatos:',
          '• Vómito',
          '• Diarrea',
          '• Letargo',
          '• Cambios en el color de orina',
          '• Temblores (en casos severos)',
          '',
          'MONSTERA DELICIOSA (Costilla de Adán):',
          'Contiene oxalatos de calcio.',
          '',
          'Efectos:',
          '• Irritación oral severa',
          '• Babeo',
          '• Dificultad para tragar',
          '• Hinchazón de boca',
          '',
          'SANSEVIERA/ESPADA DE SAN JORGE:',
          'Contiene saponinas.',
          '',
          'Síntomas:',
          '• Náusea',
          '• Vómito',
          '• Diarrea',
          '',
          'JADE (Crassula ovata):',
          'Toxicidad leve a moderada.',
          '',
          'Síntomas:',
          '• Vómito',
          '• Depresión',
          '• Ataxia (pérdida de coordinación)',
          '• Ritmo cardíaco lento (raro)',
        ],
      },
      {
        title: 'Plantas de Exterior y Jardín',
        content: [
          'AZALEAS Y RODODENDROS:',
          'Altamente tóxicos, todas las partes.',
          '',
          'Toxina: Grayanotoxinas',
          '',
          'Síntomas (aparecen en minutos a horas):',
          '• Vómito',
          '• Diarrea',
          '• Babeo',
          '• Debilidad',
          '• Depresión del sistema nervioso central',
          '• Ritmo cardíaco anormal',
          '• Coma',
          '• Puede ser mortal',
          '',
          'OLEANDRO (Nerium oleander):',
          'EXTREMADAMENTE TÓXICO, potencialmente mortal.',
          '',
          'Afecta el corazón:',
          '• Arritmias cardíacas',
          '• Vómito',
          '• Diarrea con sangre',
          '• Salivación',
          '• Colapso',
          '• Muerte',
          '',
          'TULIPANES Y NARCISOS:',
          'El bulbo es la parte más tóxica.',
          '',
          'Síntomas:',
          '• Irritación gastrointestinal',
          '• Babeo',
          '• Pérdida de apetito',
          '• Depresión del SNC',
          '• Convulsiones (raras)',
          '',
          'CICLAMEN:',
          'La raíz/tubérculo es muy tóxico.',
          '',
          'Síntomas:',
          '• Vómito severo',
          '• Diarrea',
          '• Ritmo cardíaco anormal',
          '• Convulsiones',
        ],
      },
      {
        title: 'Plantas Festivas Peligrosas',
        content: [
          'FLOR DE PASCUA/NOCHEBUENA (Poinsettia):',
          'Contrario a la creencia popular, toxicidad leve.',
          '',
          'Síntomas (generalmente leves):',
          '• Irritación leve de boca',
          '• Vómito ocasional',
          '• Diarrea rara',
          '',
          'Nota: No tan peligrosa como se pensaba, pero evita igualmente.',
          '',
          'MUÉRDAGO:',
          'Tóxico para perros y gatos.',
          '',
          'Síntomas:',
          '• Vómito',
          '• Diarrea',
          '• Dificultad respiratoria',
          '• Ritmo cardíaco lento',
          '• Presión arterial baja',
          '• En grandes cantidades: colapso, muerte',
          '',
          'ACEBO (Holly):',
          'Las bayas son particularmente tóxicas.',
          '',
          'Síntomas:',
          '• Vómito',
          '• Diarrea',
          '• Depresión',
        ],
      },
      {
        title: 'Qué Hacer si tu Mascota Come Planta Tóxica',
        content: [
          'PASOS INMEDIATOS:',
          '',
          '1. IDENTIFICA la planta:',
          '• Si es posible, toma foto',
          '• Guarda muestra',
          '• Anota nombre si lo conoces',
          '',
          '2. RETIRA cualquier material vegetal de la boca',
          '• Con cuidado, sin forzar',
          '• Usa guantes si es posible',
          '',
          '3. CONTACTA al veterinario o toxicología INMEDIATAMENTE:',
          '• Describe la planta',
          '• Cantidad aproximada ingerida',
          '• Tiempo transcurrido',
          '• Síntomas presentes',
          '',
          '4. NO INDUZCAS VÓMITO sin instrucción:',
          '• Para algunas plantas puede empeorar',
          '• Especialmente si hay irritación oral',
          '',
          '5. SI hay irritación oral:',
          '• Enjuaga boca con agua fresca',
          '• Ofrece leche o agua (si está consciente)',
          '• Evita que se rasque la boca',
          '',
          '6. MONITOREA respiración y estado general',
          '',
          '7. LLEVA AL VETERINARIO:',
          '• Incluso si los síntomas parecen leves',
          '• Lleva muestra de la planta',
          '',
          'PREVENCIÓN:',
          '',
          '• Identifica todas las plantas en tu hogar',
          '• Coloca plantas tóxicas fuera de alcance',
          '• Considera eliminar plantas muy tóxicas',
          '• Opta por alternativas pet-friendly',
          '• Supervisa a mascotas cerca de plantas',
        ],
      },
      {
        title: 'Alternativas Seguras para Mascotas',
        content: [
          'Plantas que son seguras para perros y gatos:',
          '',
          'PLANTAS DE INTERIOR SEGURAS:',
          '• Orquídea (Phalaenopsis)',
          '• Palma Areca',
          '• Planta araña (Chlorophytum)',
          '• Violeta africana',
          '• Helecho de Boston',
          '• Calathea (la mayoría)',
          '• Peperomia',
          '• Maranta (planta de oración)',
          '',
          'SUCULENTAS SEGURAS:',
          '• Echeveria',
          '• Haworthia',
          '• Algunos tipos de Sedum',
          '',
          'HIERBAS SEGURAS:',
          '• Albahaca',
          '• Tomillo',
          '• Romero',
          '• Hierba gatera (para gatos)',
          '',
          'IMPORTANTE:',
          'Siempre verifica cada planta específica antes de traerla a casa.',
          'La variedad exacta puede afectar la seguridad.',
          '',
          'Recursos útiles:',
          '• ASPCA Poison Control: lista completa de plantas tóxicas',
          '• Consulta con tu veterinario',
          '• Apps de identificación de plantas pueden ayudar',
        ],
      },
    ],
  },
  '6': {
    title: 'Comportamiento de Dolor en Mascotas',
    category: 'Cuidados Básicos',
    readTime: '12 min',
    categoryColor: 'bg-emerald-100 text-emerald-700 border-emerald-300',
    image: 'https://images.unsplash.com/photo-1707764075738-d3689b15764d?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHxkb2clMjBwYWluJTIwYmVoYXZpb3J8ZW58MXx8fHwxNzYyMDMwNTU3fDA&ixlib=rb-4.1.0&q=80&w=1080',
    sections: [
      {
        title: 'Por Qué las Mascotas Ocultan el Dolor',
        content: [
          'Los animales instintivamente esconden signos de dolor y debilidad.',
          '',
          'Razones evolutivas:',
          '• En la naturaleza, mostrar debilidad atrae predadores',
          '• Los animales enfermos son excluidos del grupo',
          '• Instinto de supervivencia profundamente arraigado',
          '',
          'Implicaciones para dueños:',
          '• Para cuando notes el dolor, puede ser severo',
          '• Los signos sutiles son críticos',
          '• Necesitas conocer muy bien el comportamiento normal',
          '• Cambios pequeños pueden indicar problemas grandes',
          '',
          'Por esto es esencial:',
          '• Observar diariamente a tu mascota',
          '• Conocer sus patrones normales',
          '• Detectar cambios tempranos',
          '• No ignorar señales sutiles',
        ],
      },
      {
        title: 'Signos de Dolor en Perros',
        content: [
          'CAMBIOS DE COMPORTAMIENTO:',
          '• Menos activo, reacio a moverse',
          '• No quiere subir escaleras o saltar',
          '• Se retira o esconde más',
          '• Agresión inusual al tocarlo',
          '• Menos interés social',
          '• Cambios en patrones de sueño',
          '• Inquietud constante',
          '',
          'SIGNOS FÍSICOS:',
          '• Cojera o caminar rígido',
          '• Postura encorvada',
          '• Respiración rápida o superficial',
          '• Temblores musculares',
          '• No puede ponerse cómodo',
          '• Se levanta y acuesta repetidamente',
          '',
          'EXPRESIÓN FACIAL CANINA DEL DOLOR:',
          '• Ojos entrecerrados o vidriosos',
          '• Orejas hacia atrás, aplastadas',
          '• Ceño fruncido',
          '• Mirada ausente o fija',
          '• Pupilas dilatadas',
          '',
          'VOCALIZACIÓN:',
          '• Quejidos o gemidos',
          '• Ladridos al ser tocado',
          '• Jadeo excesivo sin ejercicio',
          '• Aullidos (dolor severo)',
          '',
          'CAMBIOS DE APETITO:',
          '• Come menos o rechaza comida',
          '• Dificultad para masticar',
          '• Prefiere alimentos blandos',
          '• Acerca la cabeza al plato pero no come',
        ],
      },
      {
        title: 'Signos de Dolor en Gatos',
        content: [
          'Los gatos son maestros ocultando dolor. Los signos son más sutiles.',
          '',
          'CAMBIOS DE COMPORTAMIENTO:',
          '• Menos acicalamiento (pelaje descuidado, opaco)',
          '• Acicalamiento excesivo en un área específica',
          '• Evita saltar a lugares que antes usaba',
          '• Se esconde más de lo normal',
          '• Menos juego e interacción',
          '• Cambios en rutina de sueño',
          '• Evita ser tocado en áreas específicas',
          '',
          'EXPRESIÓN FACIAL FELINA DEL DOLOR:',
          'La "Escala de Mueca Felina" identifica:',
          '• Orejas aplanadas hacia los lados (no hacia atrás)',
          '• Ojos entrecerrados o cerrados parcialmente',
          '• Bigotes hacia adelante y tensos',
          '• Hocico tenso, forma elíptica',
          '• Cabeza por debajo del nivel de hombros',
          '• Posición de "cabeza presionada" contra superficies',
          '',
          'POSTURA Y MOVILIDAD:',
          '• Posición "en bola" muy cerrada',
          '• Reacio a moverse',
          '• Postura rígida al sentarse',
          '• Camina con espalda arqueada',
          '• Cojera sutil',
          '',
          'USO DE CAJA DE ARENA:',
          'Cambios son señal común de dolor:',
          '• Evita la caja (dolor al agacharse)',
          '• Elimina fuera de la caja',
          '• Entra y sale rápidamente sin usar',
          '• Maúlla en la caja',
          '• Postura anormal al usarla',
          '',
          'VOCALIZACIÓN:',
          '• Maullidos inusuales o más frecuentes',
          '• Gruñidos o siseos cuando lo tocas',
          '• Ronroneo constante (puede indicar dolor, no siempre felicidad)',
          '• Silencio inusual en gatos normalmente vocales',
        ],
      },
      {
        title: 'Tipos de Dolor: Agudo vs Crónico',
        content: [
          'DOLOR AGUDO:',
          'Aparición súbita, generalmente intenso.',
          '',
          'Causas comunes:',
          '• Lesiones traumáticas (golpes, caídas)',
          '• Heridas o quemaduras',
          '• Cirugía reciente',
          '• Infecciones agudas (oído, dental)',
          '• Obstrucción intestinal',
          '• Torsión gástrica',
          '• Pancreatitis',
          '',
          'Signos característicos:',
          '• Cambio REPENTINO de comportamiento',
          '• Vocalización aguda',
          '• Rechazo rotundo a ser tocado',
          '• Respiración rápida, superficial',
          '• Postura anormal marcada',
          '• Agitación extrema',
          '',
          'Acción: VETERINARIO INMEDIATO',
          '',
          'DOLOR CRÓNICO:',
          'Se desarrolla gradualmente, persiste semanas o meses.',
          '',
          'Causas comunes:',
          '• Artritis/osteoartritis',
          '• Enfermedad dental avanzada',
          '• Cáncer',
          '• Enfermedad renal',
          '• Cistitis intersticial (gatos)',
          '• Neuropatías',
          '',
          'Signos característicos:',
          '• Cambios sutiles durante semanas/meses',
          '• Disminución gradual de actividad',
          '• Cambios de personalidad lentos',
          '• Pérdida de peso progresiva',
          '• "Simplemente está envejeciendo" (ERROR COMÚN)',
          '',
          'Acción: Consulta veterinaria pronto',
          'El dolor crónico es tratable, mejora calidad de vida significativamente.',
        ],
      },
      {
        title: 'Evaluación del Dolor en Casa',
        content: [
          'Observa estos cinco aspectos diariamente:',
          '',
          '1. MOVILIDAD:',
          '• ¿Salta normalmente a muebles, cama?',
          '• ¿Sube/baja escaleras sin dificultad?',
          '• ¿Camina sin cojear?',
          '• ¿Se levanta fácilmente después de descansar?',
          '• ¿Juega con energía normal?',
          '• ¿Sacude el cuerpo completamente?',
          '',
          '2. APETITO E HIDRATACIÓN:',
          '• ¿Come con entusiasmo habitual?',
          '• ¿Mastica sin problemas?',
          '• ¿Ha cambiado preferencias (solo comida blanda)?',
          '• ¿Bebe agua normalmente?',
          '',
          '3. INTERACCIÓN SOCIAL:',
          '• ¿Busca atención como antes?',
          '• ¿Responde a llamados y juegos?',
          '• ¿Evita ser acariciado?',
          '• ¿Agresión nueva cuando lo tocas?',
          '',
          '4. HIGIENE Y APARIENCIA:',
          '• Perros: ¿Se lame/acicala normalmente?',
          '• Gatos: ¿Pelaje brillante, limpio, sin nudos?',
          '• ¿Cambios en postura o forma de caminar?',
          '',
          '5. DESCANSO:',
          '• ¿Duerme en posiciones normales?',
          '• ¿Parece cómodo?',
          '• ¿Se levanta sin esfuerzo?',
          '• ¿Inquietud nocturna?',
          '',
          'TEST DE PALPACIÓN GENTIL (si tu mascota lo permite):',
          '',
          'Con cuidado extremo:',
          '• Toca diferentes áreas del cuerpo',
          '• Observa reacciones (tensión, quejido, retirarse)',
          '• Compara lados izquierdo y derecho',
          '• DETÉN inmediatamente si muestra incomodidad',
          '',
          'NUNCA fuerces el examen si causa angustia.',
        ],
      },
      {
        title: 'Dolor por Ubicación: Signos Específicos',
        content: [
          'DOLOR ABDOMINAL:',
          '• Postura encorvada, espalda arqueada',
          '• Abdomen tenso, "tablón"',
          '• Gemidos al levantarse',
          '• Resistencia al tocar vientre',
          '• Posición de "rezo" (pecho abajo, trasero arriba)',
          '',
          'DOLOR DENTAL/ORAL:',
          '• Babeo excesivo',
          '• Mal aliento repentino',
          '• Mastica de un solo lado',
          '• Deja caer comida',
          '• Frota cara con pata',
          '• Hinchazón facial',
          '',
          'DOLOR DE OÍDO:',
          '• Sacude la cabeza frecuentemente',
          '• Rasca o frota oído',
          '• Inclina cabeza hacia un lado',
          '• Llanto al tocar oreja',
          '• Pérdida de balance',
          '',
          'DOLOR DE ESPALDA/CUELLO:',
          '• Rigidez al girar',
          '• Grita al ser levantado',
          '• Postura rígida',
          '• Evita mirar hacia arriba/abajo',
          '• Posible debilidad en patas',
          '',
          'DOLOR EN EXTREMIDADES:',
          '• Cojera (puede alternar patas)',
          '• Lame constantemente una pata',
          '• No apoya peso en pata',
          '• Hinchazón en articulación',
          '• Evita tocar piso con pata',
        ],
      },
      {
        title: 'Cuándo Buscar Ayuda Veterinaria',
        content: [
          'EMERGENCIA VETERINARIA INMEDIATA si:',
          '',
          '• Vocalización constante de dolor',
          '• No puede levantarse o caminar',
          '• Respiración muy rápida o dificultosa',
          '• Abdomen tenso y doloroso',
          '• No come ni bebe por más de 24 horas',
          '• Vómito persistente con signos de dolor',
          '• Trauma reciente (atropello, caída)',
          '• Sangrado activo',
          '• Hinchazón repentina de abdomen',
          '• Colapso o extrema debilidad',
          '• Llanto al orinar/defecar',
          '',
          'CITA VETERINARIA PRONTO (1-2 días) si:',
          '',
          '• Cojera que persiste más de 24 horas',
          '• Disminución gradual de actividad',
          '• Cambios sutiles pero persistentes de comportamiento',
          '• Menor interés en actividades favoritas',
          '• Cambios leves en apetito',
          '• Mascotas mayores con signos nuevos',
          '• Cualquier cambio que te preocupe',
          '',
          'NO IGNORES CAMBIOS EN MASCOTAS MAYORES:',
          '"Está viejo" NO es un diagnóstico.',
          'El dolor es tratable a cualquier edad.',
          'Mejora dramáticamente la calidad de vida.',
          '',
          'NUNCA AUTOMEDIQUES:',
          '• Ibuprofeno: MORTAL para perros y gatos',
          '• Paracetamol/Acetaminofén: MORTAL para gatos',
          '• Aspirina: peligrosa sin supervisión veterinaria',
          '• Medicamentos humanos para dolor: generalmente tóxicos',
          '',
          'SOLO da medicamentos prescritos específicamente por tu veterinario.',
        ],
      },
    ],
  },
  '7': {
    title: 'Primeros Auxilios para Heridas Leves',
    category: 'Cuidados Básicos',
    readTime: '15 min',
    categoryColor: 'bg-emerald-100 text-emerald-700 border-emerald-300',
    image: 'https://images.unsplash.com/photo-1758204054683-6e3a7d552bd0?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHx3b3VuZCUyMGJhbmRhZ2luZyUyMGZpcnN0JTIwYWlkfGVufDF8fHx8MTc2MjAzMTg1MXww&ixlib=rb-4.1.0&q=80&w=1080',
    sections: [
      {
        title: 'Cuándo Puedes Tratar en Casa vs Cuándo Ir al Veterinario',
        content: [
          'PUEDES TRATAR EN CASA (después de evaluación cuidadosa):',
          '',
          'Heridas LEVES:',
          '• Rasguños superficiales',
          '• Cortes pequeños (menos de 1 cm)',
          '• Abrasiones por rozamiento',
          '• Almohadillas ligeramente raspadas',
          '• Uña rota menor sin sangrado excesivo',
          '',
          'Criterios:',
          '• Sangrado mínimo que se detiene con presión',
          '• No profunda',
          '• Bordes limpios',
          '• Tu mascota permite que la examines',
          '• No en área sensible (ojos, genitales)',
          '',
          'REQUIERE VETERINARIO:',
          '',
          'Heridas GRAVES:',
          '• Sangrado que no se detiene en 5-10 minutos',
          '• Cortes profundos (ves grasa, músculo, hueso)',
          '• Heridas grandes (más de 2-3 cm)',
          '• Heridas punzantes (mordeduras, clavos)',
          '• Heridas en cara, cuello, abdomen, pecho',
          '• Heridas con cuerpos extraños incrustados',
          '• Heridas infectadas (pus, mal olor, muy rojas)',
          '• Quemaduras',
          '• Tu mascota está en shock',
          '',
          'SIGNOS DE SHOCK:',
          '• Encías pálidas o blancas',
          '• Respiración rápida, superficial',
          '• Pulso débil, rápido',
          '• Debilidad extrema',
          '• Temperatura baja',
          '',
          'Si hay CUALQUIER duda, consulta veterinario.',
        ],
      },
      {
        title: 'Preparación y Seguridad',
        content: [
          'ANTES DE TRATAR CUALQUIER HERIDA:',
          '',
          '1. PROTÉGETE:',
          '• Lávate las manos',
          '• Usa guantes desechables si tienes',
          '• Mascotas con dolor pueden morder',
          '• Ten cuidado incluso con mascotas dóciles',
          '',
          '2. EVALÚA NECESIDAD DE BOZAL:',
          'Considera bozal temporal si:',
          '• Tu mascota muestra signos de dolor agudo',
          '• Gruñe o intenta morder',
          '• Es muy ansiosa',
          '',
          'Cómo hacer bozal de emergencia (SOLO perros):',
          '• Usa venda o tira de tela larga',
          '• Haz lazo alrededor del hocico',
          '• Ata debajo de la mandíbula',
          '• Ata detrás de las orejas',
          '',
          'NUNCA uses bozal en:',
          '• Gatos (pueden vomitar y asfixiarse)',
          '• Perros braquicéfalos (Bulldogs, Pugs)',
          '• Mascotas con dificultad respiratoria',
          '• Mascotas vomitando',
          '',
          '3. REÚNE SUMINISTROS:',
          '• Guantes',
          '• Solución salina estéril o agua limpia',
          '• Gasa estéril',
          '• Vendas',
          '• Cinta adhesiva médica',
          '• Antiséptico (clorhexidina diluida)',
          '• Tijeras',
          '',
          '4. PIDE AYUDA:',
          'Tener alguien que sostenga a tu mascota facilita el proceso.',
        ],
      },
      {
        title: 'Paso a Paso: Limpiar y Tratar Heridas Leves',
        content: [
          'PASO 1: DETENER EL SANGRADO',
          '',
          'Si hay sangrado activo:',
          '• Aplica presión directa con gasa limpia',
          '• Mantén presión constante 5-10 minutos',
          '• NO levantes para revisar constantemente',
          '• Eleva el área si es posible',
          '',
          'Si no se detiene en 10 minutos: VETERINARIO',
          '',
          'PASO 2: LIMPIAR LA HERIDA',
          '',
          'Una vez detenido el sangrado:',
          '',
          '1. Recorta pelo alrededor (opcional):',
          '• Con cuidado, usa tijeras de punta roma',
          '• Ayuda a mantener área limpia',
          '• Evita que pelo entre en herida',
          '',
          '2. Enjuaga abundantemente:',
          '• Usa solución salina estéril (mejor opción)',
          '• O agua limpia tibia',
          '• Enjuaga por 2-3 minutos',
          '• Remueve suciedad, escombros',
          '',
          '3. Limpia con antiséptico:',
          '• Clorhexidina diluida (0.05-0.1%)',
          '• O betadine diluido (color té suave)',
          '• Aplica con gasa limpia',
          '• Limpia desde el centro hacia afuera',
          '',
          'NO USES:',
          '• Peróxido de hidrógeno (daña tejido)',
          '• Alcohol (muy doloroso, daña tejido)',
          '• Productos no veterinarios',
          '',
          'PASO 3: SECAR',
          '',
          '• Seca gentilmente con gasa limpia',
          '• No frotes',
          '• Toquecitos suaves',
        ],
      },
      {
        title: 'Aplicar Pomada y Vendaje',
        content: [
          'APLICAR POMADA ANTIBIÓTICA:',
          '',
          'Pomadas seguras:',
          '• Pomadas antibióticas veterinarias',
          '• Neosporin SIMPLE (triple antibiótico)',
          '',
          'EVITA pomadas con:',
          '• Corticosteroides',
          '• Anestésicos (pueden ser tóxicos si lamen)',
          '• Ingredientes desconocidos',
          '',
          'Aplicación:',
          '• Capa delgada',
          '• Cubre toda la herida',
          '• No apliques exceso',
          '',
          'VENDAJE (si es necesario):',
          '',
          'Cuándo vendaría:',
          '• Heridas en patas/almohadillas',
          '• Áreas que tu mascota puede lamer',
          '• Heridas que necesitan protección de suciedad',
          '',
          'Cómo vendar correctamente:',
          '',
          '1. Primera capa - Gasa no adherente:',
          '• Directamente sobre la herida',
          '• Cubre completamente',
          '',
          '2. Segunda capa - Algodón o gasa acolchada:',
          '• Proporciona amortiguación',
          '• Absorbe drenaje',
          '',
          '3. Tercera capa - Venda cohesiva:',
          '• Sostiene todo en lugar',
          '• NO muy apretada',
          '• Debes poder pasar 2 dedos debajo',
          '',
          'IMPORTANTE:',
          '• Nunca vendas demasiado apretado',
          '• Revisa circulación (dedos no hinchados, no azules)',
          '• Cambia vendaje diariamente',
          '• Mantén seco',
          '',
          'Señales de vendaje muy apretado:',
          '• Hinchazón arriba o abajo del vendaje',
          '• Dedos fríos',
          '• Cojera aumentada',
          '• Olor malo',
          '• Tu mascota muy molesta',
        ],
      },
      {
        title: 'Prevenir que Lama o Muerda',
        content: [
          'Las mascotas instintivamente lamen heridas, pero esto puede:',
          '• Introducir bacterias',
          '• Impedir cicatrización',
          '• Causar infección',
          '• Reabrir herida',
          '',
          'MÉTODOS DE PREVENCIÓN:',
          '',
          '1. COLLAR ISABELINO (Cono):',
          'Método más efectivo.',
          '',
          'Opciones:',
          '• Plástico rígido tradicional',
          '• Inflable (más cómodo)',
          '• Suave de tela',
          '',
          'Asegúrate:',
          '• Tamaño correcto (llega más allá del hocico)',
          '• Ajustado pero no muy apretado',
          '• Tu mascota puede comer/beber',
          '',
          '2. ROPA PROTECTORA:',
          '• Camisetas para perros',
          '• Bodies post-quirúrgicos',
          '• Cubren heridas en tronco',
          '',
          '3. VENDAJE PROTECTOR:',
          '• Para heridas en patas',
          '• Cambia diariamente',
          '',
          '4. DISTRAER:',
          '• Aumenta juegos',
          '• Juguetes interactivos',
          '• Más atención',
          '',
          'NO USES:',
          '• Sprays amargos directamente en herida',
          '• Métodos que causen estrés excesivo',
        ],
      },
      {
        title: 'Monitoreo y Cuidado Continuo',
        content: [
          'REVISA LA HERIDA DIARIAMENTE:',
          '',
          'Signos de BUENA cicatrización:',
          '• Bordes secos',
          '• Costra formándose',
          '• Enrojecimiento disminuyendo',
          '• Hinchazón disminuyendo',
          '• Sin pus',
          '• Sin mal olor',
          '',
          'Signos de INFECCIÓN (VE AL VETERINARIO):',
          '• Pus (descarga amarilla, verde)',
          '• Mal olor',
          '• Enrojecimiento aumentando',
          '• Hinchazón aumentando',
          '• Caliente al tacto',
          '• Dolor aumentado',
          '• Fiebre',
          '• Letargo',
          '',
          'LIMPIEZA DIARIA:',
          '',
          '1. Lava tus manos',
          '2. Retira vendaje viejo (si hay)',
          '3. Limpia con solución salina',
          '4. Seca suavemente',
          '5. Aplica pomada antibiótica',
          '6. Venda nuevo si es necesario',
          '',
          'CUÁNDO DEJAR DE VENDARÍA:',
          '• Cuando forma costra seca',
          '• No hay drenaje',
          '• Tu mascota no la molesta',
          '• Veterinario lo indica',
          '',
          'TIEMPO DE CICATRIZACIÓN:',
          'Heridas leves típicamente:',
          '• Comienzan a cerrar: 3-5 días',
          '• Cierran completamente: 7-14 días',
          '• Cicatrización completa: 2-3 semanas',
          '',
          'Si no mejora en 3-4 días: CONSULTA VETERINARIO',
        ],
      },
      {
        title: 'Casos Especiales',
        content: [
          'ALMOHADILLAS RASPADAS:',
          '',
          'Muy comunes, especialmente en verano (asfalto caliente).',
          '',
          'Tratamiento:',
          '• Limpia cuidadosamente',
          '• Aplica pomada antibiótica',
          '• Venda si tu perro lo tolera',
          '• Limita caminatas a superficies suaves',
          '• Usa botitas protectoras',
          '',
          'UÑAS ROTAS:',
          '',
          'Si solo está agrietada o rota parcialmente:',
          '• Recorta la parte suelta (si es seguro)',
          '• Detén sangrado con polvo estíptico',
          '• O harina/maicena si no tienes polvo',
          '• Mantén limpia',
          '',
          'Si está sangrando mucho o muy dolorosa: VETERINARIO',
          '',
          'HERIDAS POR LAMIDO (Hot Spots):',
          '',
          'Áreas rojas, húmedas, muy irritadas.',
          '',
          'Tratamiento:',
          '• Recorta pelo alrededor',
          '• Limpia y seca completamente',
          '• Aplica spray o crema veterinaria específica',
          '• CRUCIAL: prevenir más lamido (collar isabelino)',
          '',
          'Tienden a empeorar rápidamente si no se previene el lamido.',
          '',
          'RASGUÑOS DE GATO A GATO:',
          '',
          'Pueden parecer menores pero:',
          '• Las garras de gato tienen muchas bacterias',
          '• Alto riesgo de absceso',
          '',
          'Limpia muy bien y monitorea estrechamente.',
          'Si hay hinchazón en 24-48 horas: VETERINARIO',
        ],
      },
    ],
  },
  '8': {
    title: 'Seguridad en el Automóvil para Mascotas',
    category: 'Seguridad',
    readTime: '10 min',
    categoryColor: 'bg-orange-100 text-orange-700 border-orange-300',
    image: 'https://images.unsplash.com/photo-1595163681737-efebcbdaf076?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHxjYXIlMjBwZXQlMjBzYWZldHl8ZW58MXx8fHwxNzYyMDMxODUwfDA&ixlib=rb-4.1.0&q=80&w=1080',
    sections: [
      {
        title: 'Por Qué la Seguridad Vehicular es Crítica',
        content: [
          'Las mascotas no aseguradas en vehículos son un peligro para todos.',
          '',
          'RIESGOS PARA LA MASCOTA:',
          '',
          'En un accidente a 50 km/h:',
          '• Un perro de 30 kg ejerce fuerza de 1,100 kg',
          '• Un gato de 5 kg ejerce fuerza de 180 kg',
          '• Probabilidad de lesión grave o muerte: muy alta',
          '',
          'Sin seguridad:',
          '• Puede ser lanzado contra parabrisas',
          '• Aplastado por airbags',
          '• Lanzado fuera del vehículo',
          '• Lesiones graves incluso en frenadas bruscas',
          '',
          'RIESGOS PARA HUMANOS:',
          '',
          '• Mascota suelta es proyectil peligroso',
          '• Puede golpear a pasajeros',
          '• Puede causar accidente (distracción, interferir con pedales)',
          '• En despliegue de airbag, puede ser lanzada contra personas',
          '',
          'RIESGOS ADICIONALES:',
          '',
          '• Mascota asustada puede escapar en accidente',
          '• Puede morder a rescatistas',
          '• Dificulta evacuación de emergencia',
          '',
          'La solución: SIEMPRE asegura a tu mascota.',
        ],
      },
      {
        title: 'Opciones de Seguridad: Perros',
        content: [
          'ARNÉS DE SEGURIDAD PARA AUTOMÓVIL:',
          'Mejor opción para la mayoría de perros.',
          '',
          'Características:',
          '• Se abrocha al cinturón de seguridad',
          '• Arnés especial (no collar)',
          '• Probado en impactos',
          '• Ajustable',
          '',
          'Ventajas:',
          '• Permite cierto movimiento',
          '• Perro puede sentarse o acostarse',
          '• Más económico que jaula',
          '',
          'Cómo elegir:',
          '• Busca arneses PROBADOS EN IMPACTOS',
          '• Tamaño correcto (mide a tu perro)',
          '• Acolchado para comodidad',
          '• Puntos de anclaje reforzados',
          '',
          'Marcas recomendadas:',
          '• Busca certificaciones de seguridad',
          '• Lee reseñas',
          '• Pruebas independientes',
          '',
          'JAULA/TRANSPORTADORA ASEGURADA:',
          'Opción más segura, especialmente para perros pequeños.',
          '',
          'Características:',
          '• Plástico rígido o metal',
          '• Tamaño apropiado (perro puede estar de pie, girar)',
          '• Asegurada con cinturón o correas',
          '',
          'Ventajas:',
          '• Máxima protección',
          '• Contiene a mascota si vehículo vuelca',
          '• Previene escape en accidente',
          '',
          'Ubicación:',
          '• Asiento trasero (más seguro)',
          '• Perpendicular a dirección de viaje',
          '• Asegurada firmemente',
          '',
          'BARRERA/DIVISOR DE CARGA:',
          'Para perros grandes en SUVs o camionetas.',
          '',
          'Características:',
          '• Separa área de carga de cabina',
          '• Metal resistente',
          '• Instalación permanente o semi-permanente',
          '',
          'Combinar con:',
          '• Arnés asegurado en área de carga',
          '• O jaula en área de carga',
        ],
      },
      {
        title: 'Opciones de Seguridad: Gatos',
        content: [
          'TRANSPORTADORA ASEGURADA:',
          'ÚNICA opción segura para gatos.',
          '',
          'Nunca transportes gato suelto o solo con arnés.',
          '',
          'Tipo de transportadora:',
          '• Plástico rígido (más segura)',
          '• Tamaño: gato puede estar de pie y girar',
          '• Puerta segura que no se abre fácilmente',
          '• Ventilación adecuada',
          '• Techo removible (facilita sacar gato)',
          '',
          'CÓMO ASEGURAR LA TRANSPORTADORA:',
          '',
          'En asiento trasero:',
          '• Coloca transportadora perpendicular a dirección',
          '• Asegura con cinturón de seguridad',
          '• Cinturón pasa por asa',
          '• Ajusta firmemente',
          '',
          'Alternativa - suelo trasero:',
          '• Entre asiento delantero y trasero',
          '• Calza firmemente',
          '• No puede moverse en frenada',
          '',
          'NUNCA:',
          '• En asiento delantero',
          '• Sobre asientos sin asegurar',
          '• En el regazo del conductor',
          '• En área de carga abierta',
          '',
          'ACOSTUMBRAR A LA TRANSPORTADORA:',
          '',
          'Muchos gatos temen la transportadora.',
          '',
          'Entrenamiento:',
          '• Deja transportadora abierta en casa',
          '• Coloca mantas favoritas dentro',
          '• Alimenta golosinas dentro',
          '• Juega cerca de ella',
          '• Asociación positiva',
          '',
          'Esto reduce estrés en viajes.',
        ],
      },
      {
        title: 'Dónde NO Debe Ir tu Mascota',
        content: [
          'ASIENTO DELANTERO:',
          'NUNCA transportes mascota adelante.',
          '',
          'Razones:',
          '• Airbags pueden matarlos',
          '• Mayor impacto en colisiones frontales',
          '• Distracción para conductor',
          '• Puede interferir con controles',
          '',
          'REGAZO DEL CONDUCTOR:',
          'Extremadamente peligroso.',
          '',
          'Riesgos:',
          '• Obstruye visión',
          '• Puede interferir con volante',
          '• Puede alcanzar pedales',
          '• Causa de muchos accidentes',
          '',
          'Multas en muchas jurisdicciones.',
          '',
          'CAJA DE CAMIONETA ABIERTA:',
          'NUNCA transportes mascota en caja abierta.',
          '',
          'Peligros:',
          '• Puede saltar o caer',
          '• Lesiones por viento, escombros',
          '• Exposición a elementos',
          '• Puede estrangularse si está atada',
          '• Ilegal en muchos lugares',
          '',
          'Si DEBES usar caja de camioneta:',
          '• Jaula asegurada y cerrada',
          '• Ventilación adecuada',
          '• Protección de elementos',
          '',
          'CABEZA FUERA DE VENTANA:',
          'Evita permitir esto.',
          '',
          'Riesgos:',
          '• Escombros en ojos',
          '• Insectos',
          '• Lesiones en cabeza/cuello',
          '• Puede saltar en tráfico detenido',
          '',
          'ASIENTO SIN SUJECIÓN:',
          '• Ni siquiera en viajes cortos',
          '• Accidentes ocurren cerca de casa',
          '• Frenadas bruscas pueden lesionar',
        ],
      },
      {
        title: 'Preparación para Viajes Seguros',
        content: [
          'ANTES DE CADA VIAJE:',
          '',
          '1. EJERCICIO:',
          '• Pasea a tu perro antes',
          '• Juega con tu gato',
          '• Mascota cansada = más tranquila',
          '',
          '2. EVITA COMER JUSTO ANTES:',
          '• No alimentes 2-3 horas antes',
          '• Reduce náusea y vómito',
          '• Agua está bien (pequeñas cantidades)',
          '',
          '3. REVISIÓN DE SEGURIDAD:',
          '• Arnés o transportadora en buen estado',
          '• Sin rasgaduras o piezas rotas',
          '• Anclajes seguros',
          '',
          '4. IDENTIF ICACIÓN:',
          '• Collar con placa actualizada',
          '• Microchip registrado',
          '• Foto reciente en teléfono',
          '',
          'KIT DE VIAJE PARA MASCOTAS:',
          '',
          'Incluye:',
          '• Agua y tazón plegable',
          '• Correa extra',
          '• Bolsas para desechos',
          '• Toallas de papel',
          '• Medicamentos si toma',
          '• Registros de vacunación',
          '• Golosinas',
          '• Juguete favorito',
          '• Kit de primeros auxilios',
          '',
          'VIAJES LARGOS - PARADAS:',
          '',
          'Cada 2-3 horas:',
          '• Parada para estirar',
          '• Oportunidad de eliminar',
          '• Agua fresca',
          '• Breve paseo',
          '',
          'Durante paradas:',
          '• SIEMPRE con correa',
          '• Nunca dejes solo en vehículo',
          '• Área segura lejos de tráfico',
        ],
      },
      {
        title: 'Prevención del Golpe de Calor en Vehículos',
        content: [
          'NUNCA DEJES MASCOTA EN VEHÍCULO ESTACIONADO:',
          '',
          'Incluso con ventanas abiertas, la temperatura interior:',
          '• Alcanza 40°C en 10 minutos',
          '• Alcanza 50°C+ en 20 minutos',
          '• Puede ser mortal en 15 minutos',
          '',
          'ESTO APLICA INCLUSO:',
          '• En días nublados',
          '• Con ventanas entreabiertas',
          '• "Solo por unos minutos"',
          '• A la sombra (el sol se mueve)',
          '',
          'La temperatura externa puede ser 20°C y aun así peligroso.',
          '',
          'SI DEBES LLEVAR A TU MASCOTA:',
          '',
          'Opciones seguras:',
          '• Deja alguien en el auto con clima encendido',
          '• Lleva a tu mascota contigo',
          '• No hagas la parada si no puedes hacer lo anterior',
          '',
          'DURANTE EL VIAJE EN CLIMAS CÁLIDOS:',
          '',
          '• Aire acondicionado adecuado',
          '• Dirige ventilación hacia donde está mascota',
          '• Revisa temperatura en su área',
          '• Agua disponible',
          '• Paradas frecuentes en sombra',
          '',
          'Signos de sobrecalentamiento:',
          '• Jadeo excesivo',
          '• Babeo',
          '• Encías rojas brillantes',
          '• Debilidad',
          '',
          'Si ocurre:',
          '• DETÉN inmediatamente',
          '• Mueve a sombra',
          '• Ofrece agua',
          '• Enfría gradualmente',
          '• VETERINARIO urgente',
        ],
      },
      {
        title: 'Manejo del Mareo y Ansiedad',
        content: [
          'MAREO POR MOVIMIENTO:',
          'Común en mascotas jóvenes, pueden superarlo.',
          '',
          'Síntomas:',
          '• Babeo excesivo',
          '• Inquietud',
          '• Quejidos',
          '• Vómito',
          '• Bostezos frecuentes',
          '',
          'Prevención:',
          '',
          '• Viajes cortos frecuentes (entrenamiento)',
          '• No alimentes 2-3 horas antes',
          '• Ventilación adecuada',
          '• Mira hacia adelante (en transportadora puede ayudar)',
          '• Medicamento anti-náusea (consulta veterinario)',
          '',
          'ANSIEDAD EN EL AUTO:',
          '',
          'Síntomas:',
          '• Temblores',
          '• Jadeo',
          '• Llanto o ladrido',
          '• Inquietud extrema',
          '• Salivación',
          '',
          'Soluciones:',
          '',
          '1. DESENSIBILIZACIÓN GRADUAL:',
          '• Sentarse en auto apagado',
          '• Encender motor sin moverse',
          '• Viajes muy cortos',
          '• Aumentar gradualmente',
          '• Recompensas y elogios',
          '',
          '2. ASOCIACIONES POSITIVAS:',
          '• Golosinas en el auto',
          '• Juguetes favoritos',
          '• Destinos agradables (parque, no solo veterinario)',
          '',
          '3. CALMANTES NATURALES:',
          '• Feromonas (Adaptil para perros, Feliway para gatos)',
          '• Música calmante',
          '• Thundershirt o similar',
          '',
          '4. CONSULTA VETERINARIA:',
          '• Para casos severos',
          '• Puede recetar ansiolíticos',
          '• Útil para viajes largos',
          '',
          'NUNCA sedantes sin supervisión veterinaria.',
        ],
      },
    ],
  },
};

export function ArticleDetail({ articleId }: ArticleDetailProps) {
  const article = articleContent[articleId];

  if (!article) {
    return (
      <div className="min-h-screen bg-gradient-to-b from-amber-50 to-orange-50 p-6">
        <p>Artículo no encontrado</p>
      </div>
    );
  }

  return (
    <div className="min-h-screen bg-gradient-to-b from-amber-50 to-orange-50 pb-24 relative">
      <AnimatedBackground />
      
      {/* Header con imagen */}
      <div className="relative h-64 overflow-hidden z-10">
        {article.image && (
          <>
            <ImageWithFallback
              src={article.image}
              alt={article.title}
              className="w-full h-full object-cover"
            />
            <div className="absolute inset-0 bg-gradient-to-t from-black/70 via-black/40 to-transparent" />
          </>
        )}
        <div className="absolute bottom-0 left-0 right-0 p-6">
          <div className="mb-3 flex items-center gap-2">
            <Badge className={`${article.categoryColor} shadow-sm`}>{article.category}</Badge>
            <Badge className="bg-white/90 text-slate-700 border-slate-300 shadow-sm">
              <Clock className="size-3 mr-1" />
              {article.readTime}
            </Badge>
          </div>
          <h1 className="text-white mb-2 drop-shadow-lg">{article.title}</h1>
        </div>
      </div>

      <div className="px-6 py-6">
        {/* Contenido por secciones */}
        <div className="space-y-6">
          {article.sections.map((section: any, index: number) => (
            <Card key={index} className="bg-white border-slate-200 shadow-sm">
              <div className="p-6">
                <h2 className="text-slate-800 mb-4">{section.title}</h2>
                <div className="space-y-2">
                  {section.content.map((paragraph: string, pIndex: number) => (
                    <p
                      key={pIndex}
                      className={`text-slate-700 leading-relaxed ${
                        paragraph.startsWith('•') ? 'ml-4' : ''
                      } ${paragraph === '' ? 'h-2' : ''} ${
                        paragraph.includes('IMPORTANTE') ||
                        paragraph.includes('URGENTE') ||
                        paragraph.includes('NUNCA') ||
                        paragraph.includes('EMERGENCIA')
                          ? 'font-medium'
                          : ''
                      }`}
                    >
                      {paragraph}
                    </p>
                  ))}
                </div>
              </div>
            </Card>
          ))}
        </div>

        {/* Footer informativo */}
        <Card className="bg-blue-100 border-blue-300 mt-6">
          <div className="p-4 flex gap-3">
            <BookOpen className="size-5 text-blue-700 flex-shrink-0 mt-0.5" />
            <p className="text-blue-800">
              ¿Te resultó útil este artículo? Compártelo con otros dueños de mascotas 
              para ayudar a mantener seguras más mascotas.
            </p>
          </div>
        </Card>
      </div>
    </div>
  );
}
