import { Card } from './ui/card';
import { Badge } from './ui/badge';
import { Download, FileText, AlertTriangle, Clock } from 'lucide-react';
import { ImageWithFallback } from './figma/ImageWithFallback';
import { Button } from './ui/button';

interface GuideDetailProps {
  guideId: string;
}

const guideContent: Record<string, any> = {
  '1': {
    title: 'Guía Completa de Primeros Auxilios',
    readTime: '45 min',
    offline: true,
    sections: [
      {
        title: 'Evaluación Inicial del Paciente',
        content: [
          'Antes de cualquier intervención, evalúa el estado general de tu mascota:',
          '• Respuesta: ¿Está consciente y alerta?',
          '• Respiración: Observa si respira normalmente (15-30 respiraciones/minuto en perros, 20-30 en gatos)',
          '• Pulso: Siente el pulso en la arteria femoral interna del muslo (70-180 latidos/minuto en perros, 140-220 en gatos)',
          '• Mucosas: Las encías deben ser rosadas, no pálidas, azules o blancas',
          '• Temperatura: Normal entre 38-39°C',
        ],
      },
      {
        title: 'ABC de Emergencias Veterinarias',
        content: [
          'Sigue este protocolo en orden de prioridad:',
          '',
          'A - Vías Aéreas (Airway):',
          '• Asegura que las vías respiratorias estén despejadas',
          '• Retira cualquier obstrucción visible de la boca',
          '• Extiende suavemente el cuello',
          '',
          'B - Respiración (Breathing):',
          '• Verifica que respire adecuadamente',
          '• Si no respira, inicia ventilación artificial',
          '• 20-30 respiraciones por minuto',
          '',
          'C - Circulación (Circulation):',
          '• Verifica el pulso y frecuencia cardíaca',
          '• Controla cualquier sangrado severo',
          '• Mantén a la mascota caliente',
        ],
      },
      {
        title: 'Control de Hemorragias',
        content: [
          'Para sangrado externo moderado a severo:',
          '1. Aplica presión directa con gasa estéril o tela limpia',
          '2. Mantén la presión durante 3-5 minutos sin levantar',
          '3. Si la sangre traspasa, añade más gasa encima (no retires la primera)',
          '4. Una vez controlado, venda la herida sin apretar en exceso',
          '5. Busca atención veterinaria inmediata',
          '',
          'NUNCA uses torniquetes salvo en amputaciones o sangrado arterial incontrolable.',
        ],
      },
      {
        title: 'Signos de Shock',
        content: [
          'El shock es una emergencia que pone en riesgo la vida. Signos:',
          '• Mucosas pálidas o grises',
          '• Pulso débil y rápido',
          '• Respiración rápida y superficial',
          '• Temperatura corporal baja',
          '• Letargo o inconsciencia',
          '• Pupilas dilatadas',
          '',
          'Tratamiento inmediato:',
          '• Acuesta a la mascota de lado',
          '• Mantén caliente con mantas',
          '• Eleva ligeramente las patas traseras',
          '• NO des agua ni comida',
          '• Busca atención veterinaria URGENTE',
        ],
      },
      {
        title: 'Transporte de Emergencia',
        content: [
          'Cómo trasladar una mascota lesionada de forma segura:',
          '',
          'Para animales pequeños (hasta 15 kg):',
          '• Usa una caja o transportadora',
          '• Coloca una manta en el fondo',
          '• Minimiza el movimiento',
          '',
          'Para animales medianos/grandes:',
          '• Usa una tabla o superficie rígida como camilla',
          '• Solicita ayuda para levantarlo',
          '• Sujeta con cuidado pero firmemente',
          '• Mantén la columna lo más recta posible',
          '',
          'Si sospechas fractura de columna, inmoviliza completamente antes de mover.',
        ],
      },
    ],
  },
  '2': {
    title: 'Reconocimiento de Síntomas Críticos',
    readTime: '25 min',
    offline: true,
    sections: [
      {
        title: 'Signos de Emergencia Inmediata',
        content: [
          'Busca atención veterinaria INMEDIATA si observas:',
          '',
          '🔴 Respiratorios:',
          '• Dificultad para respirar o jadeo excesivo',
          '• Respiración con la boca abierta en gatos',
          '• Encías o lengua azuladas (cianosis)',
          '• Tos con sangre',
          '',
          '🔴 Cardiovasculares:',
          '• Colapso o desmayo',
          '• Pulso muy débil o ausente',
          '• Mucosas blancas o muy pálidas',
          '• Extremidades frías',
          '',
          '🔴 Neurológicos:',
          '• Convulsiones que duran más de 2 minutos',
          '• Pérdida súbita de conciencia',
          '• Incapacidad para mantenerse en pie',
          '• Desorientación severa',
        ],
      },
      {
        title: 'Abdomen Agudo y Distensión',
        content: [
          'La distensión abdominal repentina puede ser fatal, especialmente en razas grandes:',
          '',
          'Signos de urgencia:',
          '• Abdomen visiblemente hinchado y tenso',
          '• Intentos de vomitar sin éxito',
          '• Inquietud extrema, no puede acostarse cómodamente',
          '• Salivación excesiva',
          '• Respiración dificultosa',
          '• Encías pálidas',
          '',
          'Posible torsión gástrica (GDV): EMERGENCIA MORTAL',
          'Tiempo crítico: menos de 1-2 horas para intervención quirúrgica',
          'Razas de alto riesgo: Pastor Alemán, Gran Danés, Setter, Weimaraner',
        ],
      },
      {
        title: 'Intoxicaciones - Signos Comunes',
        content: [
          'Los signos de envenenamiento pueden aparecer en minutos u horas:',
          '',
          'Signos neurológicos:',
          '• Temblores o convulsiones',
          '• Debilidad o parálisis',
          '• Pupilas dilatadas o contraídas',
          '• Desorientación',
          '',
          'Signos digestivos:',
          '• Vómito (puede tener sangre)',
          '• Diarrea severa',
          '• Salivación excesiva',
          '• Dolor abdominal',
          '',
          'Otros signos:',
          '• Dificultad respiratoria',
          '• Arritmias cardíacas',
          '• Sangrado anormal',
          '',
          'IMPORTANTE: Si sospechas intoxicación, lleva el envase del producto sospechoso al veterinario.',
        ],
      },
      {
        title: 'Dificultad Respiratoria',
        content: [
          'Reconoce cuándo la respiración es crítica:',
          '',
          'Signos de alerta:',
          '• Respiración rápida en reposo (más de 40 respiraciones/min)',
          '• Respiración con esfuerzo evidente',
          '• Costillas visibles al respirar',
          '• Cuello extendido para respirar mejor',
          '• Ruidos anormales al respirar',
          '• Tos persistente o productiva',
          '',
          'En gatos - ESPECIALMENTE CRÍTICO:',
          '• Respiración con la boca abierta',
          '• Jadeo (los gatos normales NO jadean)',
          '• Postura con el cuello extendido',
          '',
          'Actúa inmediatamente: mantén calmado, evita estrés, traslada con urgencia.',
        ],
      },
      {
        title: 'Trauma y Accidentes',
        content: [
          'Después de un accidente vehicular, caída o ataque:',
          '',
          'Evalúa estos signos de trauma grave:',
          '• Sangrado visible o interno (abdomen tenso)',
          '• Fracturas evidentes o cojera severa',
          '• Dificultad respiratoria',
          '• Shock (mucosas pálidas, debilidad)',
          '• Cambios neurológicos',
          '',
          'IMPORTANTE:',
          'Aunque parezca estar bien, el trauma interno puede no ser evidente.',
          'Siempre busca evaluación veterinaria después de cualquier accidente.',
          '',
          'El sangrado interno puede manifestarse horas después con:',
          '• Debilidad progresiva',
          '• Mucosas cada vez más pálidas',
          '• Abdomen distendido',
          '• Colapso súbito',
        ],
      },
    ],
  },
  '3': {
    title: 'Técnicas de RCP para Mascotas',
    readTime: '20 min',
    offline: true,
    sections: [
      {
        title: 'Cuándo Realizar RCP',
        content: [
          'Realiza RCP SOLO si tu mascota:',
          '• No responde a estímulos',
          '• No respira o respira con agonía',
          '• No tiene pulso palpable',
          '',
          'IMPORTANTE: La RCP no se realiza en mascotas conscientes o que respiran normalmente.',
          '',
          'Antes de iniciar:',
          '1. Verifica que el entorno sea seguro',
          '2. Pide a alguien que llame al veterinario de emergencia',
          '3. Coloca a la mascota sobre una superficie firme',
          '4. Retira collar o cualquier objeto del cuello',
        ],
      },
      {
        title: 'RCP en Perros - Paso a Paso',
        content: [
          'Para perros de más de 7 kg:',
          '',
          '1. POSICIÓN:',
          '• Acuesta al perro sobre su lado derecho',
          '• Asegúrate que la superficie es firme',
          '',
          '2. VÍA AÉREA:',
          '• Extiende el cuello suavemente',
          '• Abre la boca y retira cualquier obstrucción visible',
          '• Cierra la boca y sella los labios',
          '',
          '3. VENTILACIÓN:',
          '• Coloca tu boca sobre el hocico del perro',
          '• Sopla suavemente hasta ver el pecho elevarse',
          '• Da 2 respiraciones (1-1.5 segundos cada una)',
          '',
          '4. COMPRESIONES CARDÍACAS:',
          '• Localiza el corazón (detrás del codo, mitad inferior del pecho)',
          '• Coloca las manos una sobre otra',
          '• Comprime 1/3 a 1/2 de la profundidad del pecho',
          '• Ritmo: 100-120 compresiones por minuto',
          '• Ratio: 30 compresiones : 2 respiraciones',
          '',
          'Continúa hasta que el perro respire por sí solo o llegues al veterinario.',
        ],
      },
      {
        title: 'RCP en Perros Pequeños y Gatos',
        content: [
          'Para perros de menos de 7 kg y gatos:',
          '',
          '1. POSICIÓN:',
          '• Acuesta sobre el lado derecho',
          '• Superficie firme',
          '',
          '2. COMPRESIONES:',
          '• Usa UNA sola mano o los dedos (gatos muy pequeños)',
          '• Comprime directamente sobre el corazón',
          '• Profundidad: 1/3 del ancho del pecho',
          '• Ritmo: 100-120 compresiones por minuto',
          '',
          '3. VENTILACIÓN:',
          '• Sella completamente el hocico y nariz con tu boca',
          '• Respiraciones más suaves y cortas',
          '• Ratio: 30 compresiones : 2 respiraciones',
          '',
          'PRECAUCIÓN: Las costillas de animales pequeños son más frágiles.',
        ],
      },
      {
        title: 'Técnica de Ventilación Boca-Hocico',
        content: [
          'Cómo dar respiraciones artificiales efectivas:',
          '',
          '1. PREPARACIÓN:',
          '• Extiende el cuello para abrir la vía aérea',
          '• Asegúrate que no hay obstrucciones',
          '• Cierra bien la boca del animal',
          '',
          '2. TÉCNICA PERROS:',
          '• Sella tu boca alrededor del hocico',
          '• Mantén cerrada la boca del perro',
          '• Sopla suavemente en las fosas nasales',
          '• Observa que el pecho se eleve',
          '• Si no se eleva, reposiciona el cuello',
          '',
          '3. TÉCNICA GATOS/PEQUEÑOS:',
          '• Sella tu boca sobre hocico Y nariz',
          '• Respiraciones más suaves',
          '• Volumen menor de aire',
          '',
          '4. FRECUENCIA:',
          '• 20-30 respiraciones por minuto si SOLO haces ventilación',
          '• 2 respiraciones cada 30 compresiones si haces RCP completa',
        ],
      },
      {
        title: 'Verificación y Continuidad',
        content: [
          'Durante la RCP:',
          '',
          'Cada 2 minutos (5 ciclos de 30:2):',
          '• PAUSA brevemente (5 segundos)',
          '• Verifica si hay pulso',
          '• Verifica si respira',
          '• Si NO hay cambios, continúa RCP',
          '',
          'Detén RCP si:',
          '• La mascota comienza a respirar por sí sola',
          '• Recupera el pulso',
          '• Llegas al veterinario',
          '• Han pasado 20 minutos sin respuesta',
          '',
          'DESPUÉS de la RCP:',
          'Incluso si la mascota se recupera, DEBE ser examinada por un veterinario inmediatamente. Las complicaciones pueden aparecer horas después.',
          '',
          'Estadísticas realistas:',
          'La tasa de éxito de RCP en mascotas es baja (6-8%). Sin embargo, sin RCP, la supervivencia es 0%. Siempre vale la pena intentarlo.',
        ],
      },
    ],
  },
  '4': {
    title: 'Manejo de Heridas y Sangrado',
    readTime: '22 min',
    offline: false,
    sections: [
      {
        title: 'Evaluación de Heridas',
        content: [
          'Clasifica la gravedad de la herida:',
          '',
          'HERIDAS LEVES (tratables en casa):',
          '• Rasguños superficiales',
          '• Cortes pequeños (menos de 2 cm)',
          '• Sangrado que se detiene con presión en 5 minutos',
          '• Sin exposición de tejidos profundos',
          '',
          'HERIDAS GRAVES (requieren veterinario):',
          '• Heridas profundas o punzantes',
          '• Cortes mayores a 2 cm',
          '• Sangrado que no se detiene',
          '• Exposición de músculo, hueso o grasa',
          '• Heridas en cara, pecho o abdomen',
          '• Mordeduras de otros animales',
          '• Heridas contaminadas con suciedad',
        ],
      },
      {
        title: 'Control de Hemorragias',
        content: [
          'Técnica de presión directa:',
          '',
          '1. Usa gasa estéril o tela limpia',
          '2. Aplica presión FIRME directamente sobre la herida',
          '3. Mantén durante 3-5 minutos SIN levantar',
          '4. Si la sangre traspasa, añade MÁS gasa encima',
          '5. NO retires las primeras gasas (alteraría la coagulación)',
          '',
          'Para sangrado en extremidades:',
          '• Aplica presión directa primero',
          '• Puedes elevar la extremidad por encima del corazón',
          '• Si no se detiene, aplica presión en el punto de presión arterial',
          '',
          'Puntos de presión arterial:',
          '• Patas delanteras: arteria braquial (interior de la "axila")',
          '• Patas traseras: arteria femoral (ingle)',
          '',
          'NUNCA uses torniquetes excepto en:',
          '• Amputaciones traumáticas',
          '• Sangrado arterial masivo que no responde a presión',
        ],
      },
      {
        title: 'Limpieza de Heridas Menores',
        content: [
          'Para heridas superficiales que puedes tratar en casa:',
          '',
          '1. PREPARACIÓN:',
          '• Lávate bien las manos',
          '• Usa guantes si es posible',
          '• Ten listo: agua limpia, solución salina, gasa estéril',
          '',
          '2. LIMPIEZA:',
          '• Recorta el pelo alrededor de la herida (opcional)',
          '• Irriga con agua limpia o solución salina abundante',
          '• Retira suciedad y restos visibles',
          '• NO uses alcohol, peróxido de hidrógeno o yodo - dañan el tejido',
          '',
          '3. ANTISEPSIA:',
          '• Usa clorhexidina diluida (0.05%) si está disponible',
          '• Aplica con gasa estéril',
          '',
          '4. PROTECCIÓN:',
          '• Cubre con gasa estéril',
          '• Venda ligeramente (no apretado)',
          '• Cambia el vendaje diariamente',
          '',
          'Monitorea signos de infección: enrojecimiento creciente, calor, hinchazón, pus, olor fétido.',
        ],
      },
      {
        title: 'Heridas Especiales',
        content: [
          'MORDEDURAS:',
          '• SIEMPRE requieren atención veterinaria',
          '• Alto riesgo de infección',
          '• Pueden tener daño profundo no visible',
          '• Limpia superficialmente y busca atención URGENTE',
          '• Pueden necesitar antibióticos',
          '',
          'HERIDAS PUNZANTES:',
          '• Muy peligrosas - el daño interno puede ser grave',
          '• NO retires objetos empalados',
          '• NO pruebes la profundidad',
          '• Cubre y estabiliza el objeto si está presente',
          '• Veterinario URGENTE',
          '',
          'HERIDAS ABDOMINALES:',
          '• Si hay órganos visibles, NO intentes reintroducirlos',
          '• Cubre con gasa estéril HÚMEDA (solución salina)',
          '• Cubre con film plástico para evitar desecación',
          '• Veterinario URGENTE - emergencia crítica',
          '',
          'HERIDAS EN ALMOHADILLAS:',
          '• Sangran mucho pero rara vez son graves',
          '• Limpia bien y aplica presión',
          '• Venda firmemente',
          '• Usa un calcetín o bolsa sobre el vendaje al salir',
        ],
      },
      {
        title: 'Vendajes Básicos',
        content: [
          'Técnica de vendaje en 3 capas:',
          '',
          'CAPA 1 - Contacto:',
          '• Gasa estéril directamente sobre la herida',
          '• Puede estar impregnada con pomada antibiótica',
          '',
          'CAPA 2 - Acolchado:',
          '• Algodón o vendaje acolchado',
          '• Proporciona absorción y protección',
          '• Envuelve con tensión uniforme',
          '',
          'CAPA 3 - Protección:',
          '• Venda cohesiva o esparadrapo',
          '• Mantiene todo en su lugar',
          '• NO debe estar demasiado apretado',
          '',
          'VERIFICACIÓN:',
          '• Debe poder pasar un dedo bajo el vendaje',
          '• Dedos o uñas no deben hincharse',
          '• Si el vendaje se moja, cámbíalo inmediatamente',
          '• Revisa dos veces al día',
          '',
          'Signos de vendaje muy apretado:',
          '• Hinchazón de dedos/extremidad',
          '• Dedos fríos',
          '• Mal olor',
          '• La mascota se muestra muy molesta',
        ],
      },
    ],
  },
  '5': {
    title: 'Intoxicaciones Comunes',
    readTime: '35 min',
    offline: true,
    sections: [
      {
        title: 'Toxinas Alimentarias Comunes',
        content: [
          'CHOCOLATE:',
          '• Tóxico para perros y gatos',
          '• Más oscuro = más peligroso',
          '• Signos: vómito, diarrea, hiperactividad, temblores, convulsiones',
          '• Aparecen en 2-4 horas',
          '• Busca atención INMEDIATA',
          '',
          'XILITOL (edulcorante):',
          '• EXTREMADAMENTE tóxico para perros',
          '• Presente en: chicles, caramelos, mantequilla de maní',
          '• Causa hipoglucemia severa en 30 minutos',
          '• Puede causar fallo hepático',
          '• URGENCIA EXTREMA',
          '',
          'UVAS Y PASAS:',
          '• Tóxicas para perros (causa no conocida)',
          '• Pueden causar fallo renal agudo',
          '• Signos: vómito, letargo, pérdida de apetito',
          '• Cualquier cantidad es peligrosa',
          '',
          'CEBOLLA Y AJO:',
          '• Tóxicos para perros y gatos',
          '• Dañan glóbulos rojos',
          '• Signos aparecen en días: debilidad, encías pálidas',
          '• Todas las formas: crudo, cocido, en polvo',
        ],
      },
      {
        title: 'Medicamentos Humanos Peligrosos',
        content: [
          'IBUPROFENO Y ASPIRINA:',
          '• Altamente tóxicos para mascotas',
          '• Causan úlceras gástricas y fallo renal',
          '• Signos: vómito con sangre, heces negras, debilidad',
          '• NUNCA des medicamentos humanos sin consultar veterinario',
          '',
          'PARACETAMOL (Acetaminofén):',
          '• Mortal para gatos incluso en dosis pequeñas',
          '• Peligroso para perros',
          '• Causa daño hepático y destrucción de glóbulos rojos',
          '',
          'ANTIDEPRESIVOS Y ANSIOLÍTICOS:',
          '• Causa sedación, temblores, convulsiones',
          '• Afecta presión arterial y frecuencia cardíaca',
          '• Busca atención inmediata',
          '',
          'VITAMINA D:',
          '• Presente en raticidas y algunos suplementos',
          '• Causa fallo renal',
          '• Signos: vómito, aumento de sed, debilidad',
        ],
      },
      {
        title: 'Plantas Tóxicas',
        content: [
          'LIRIOS (EXTREMADAMENTE PELIGROSOS PARA GATOS):',
          '• Todas las partes son tóxicas',
          '• Causan fallo renal agudo en gatos',
          '• Incluso el polen o el agua del florero',
          '• URGENCIA EXTREMA - actuar en horas',
          '',
          'SAGO PALM:',
          '• Todas las partes mortales',
          '• Causa fallo hepático severo',
          '• Alta tasa de mortalidad',
          '',
          'AZALEAS Y RODODENDROS:',
          '• Afectan corazón y sistema digestivo',
          '• Vómito, diarrea, salivación',
          '• Puede causar arritmias',
          '',
          'TULIPANES Y NARCISOS:',
          '• Bulbos más tóxicos',
          '• Irritación gastrointestinal severa',
          '• Pueden causar problemas cardíacos',
          '',
          'ADELFA:',
          '• Extremadamente tóxica',
          '• Afecta corazón',
          '• Puede ser mortal',
        ],
      },
      {
        title: 'Productos del Hogar Peligrosos',
        content: [
          'ANTICONGELANTE (Etilenglicol):',
          '• EXTREMADAMENTE PELIGROSO',
          '• Sabor dulce atrae a mascotas',
          '• Mortal en cantidades muy pequeñas',
          '• Ventana de tratamiento: 8-12 horas',
          '• Signos: borrachera, vómito, convulsiones, fallo renal',
          '',
          'RATICIDAS:',
          '• Varios tipos, todos peligrosos',
          '• Anticoagulantes: causan hemorragias internas',
          '• Pueden tardar días en mostrar síntomas',
          '• GUARDA EL ENVASE para mostrar al veterinario',
          '',
          'DETERGENTES Y LIMPIADORES:',
          '• Cáusticos: dañan boca, esófago, estómago',
          '• NO provoques vómito si fueron ingeridos',
          '• Ofrece agua o leche para diluir',
          '• Busca atención veterinaria',
          '',
          'ACEITES ESENCIALES:',
          '• Especialmente tóxicos para gatos',
          '• Árbol de té, canela, cítricos, pino',
          '• Causan irritación, problemas hepáticos',
          '• Evita difusores en espacios cerrados',
        ],
      },
      {
        title: 'Qué Hacer en Caso de Intoxicación',
        content: [
          'PASOS INMEDIATOS:',
          '',
          '1. MANTÉN LA CALMA pero actúa rápido',
          '',
          '2. IDENTIFICA la toxina:',
          '• ¿Qué fue ingerido?',
          '• ¿Cuánta cantidad?',
          '• ¿Hace cuánto tiempo?',
          '• GUARDA el envase o muestra',
          '',
          '3. LLAMA al veterinario o línea de toxicología:',
          '• Describe la situación exacta',
          '• Sigue sus instrucciones al pie de la letra',
          '',
          '4. NO induzcas vómito a menos que te lo indiquen:',
          '• NUNCA si han pasado más de 2 horas',
          '• NUNCA si la sustancia es cáustica (limpiadores, lejía)',
          '• NUNCA si la mascota está inconsciente o convulsionando',
          '• NUNCA en gatos (muy peligroso)',
          '',
          '5. SI TE INDICAN INDUCIR VÓMITO:',
          '• Peróxido de hidrógeno 3% para perros',
          '• Dosis: 1 ml por cada kg de peso (máximo 45 ml)',
          '• Funciona en 10-15 minutos',
          '• Solo UN intento',
          '',
          '6. TRASLADA al veterinario inmediatamente:',
          '• Lleva el envase o muestra de la toxina',
          '• Lleva el vómito si lo hubo',
          '',
          'IMPORTANTE: El tiempo es crítico. Minutos pueden marcar la diferencia.',
        ],
      },
    ],
  },
  '6': {
    title: 'Emergencias en Cachorros y Gatitos',
    readTime: '28 min',
    offline: false,
    sections: [
      {
        title: 'Particularidades de Animales Jóvenes',
        content: [
          'Los cachorros y gatitos requieren atención especial:',
          '',
          'Vulnerabilidades:',
          '• Sistema inmune inmaduro',
          '• Menor reserva de energía (glucosa)',
          '• Deshidratación más rápida',
          '• Hipotermia más fácil',
          '• Menor capacidad de recuperación',
          '',
          'Signos vitales normales (cachorros/gatitos):',
          '• Frecuencia cardíaca: 160-200 latidos/min',
          '• Respiración: 15-40 respiraciones/min',
          '• Temperatura: 38-39°C',
          '',
          'IMPORTANTE: Cualquier emergencia en menores de 12 semanas requiere atención veterinaria URGENTE.',
        ],
      },
      {
        title: 'Hipoglucemia (Azúcar Baja)',
        content: [
          'Muy común en cachorros pequeños y razas toy:',
          '',
          'Causas:',
          '• Saltarse comidas',
          '• Estrés o ejercicio excesivo',
          '• Enfermedades parasitarias',
          '• Razas toy son especialmente vulnerables',
          '',
          'Signos:',
          '• Debilidad súbita',
          '• Temblores',
          '• Desorientación',
          '• Tambaleo',
          '• Convulsiones',
          '• Pérdida de conciencia',
          '',
          'Tratamiento inmediato:',
          '1. Frota miel, sirope de maíz o azúcar en las encías',
          '2. NO lo obligues a tragar si está inconsciente',
          '3. Mantén caliente',
          '4. Una vez consciente, ofrece comida',
          '5. Busca atención veterinaria',
          '',
          'Prevención:',
          '• Comidas pequeñas y frecuentes (4-6 veces al día)',
          '• Evita ayunos prolongados',
          '• Ten miel a mano siempre',
        ],
      },
      {
        title: 'Hipotermia en Neonatos',
        content: [
          'Los recién nacidos no regulan bien su temperatura:',
          '',
          'Temperatura normal neonatos:',
          '• Semana 1: 35.5-37°C',
          '• Semana 2-4: 36-38°C',
          '• Después de 4 semanas: 38-39°C',
          '',
          'Signos de hipotermia:',
          '• Frío al tacto',
          '• Letargo extremo',
          '• No mama',
          '• Llanto débil o ausente',
          '• Piel fría, especialmente extremidades',
          '',
          'Tratamiento:',
          '1. Calienta GRADUALMENTE (no rápido)',
          '2. Usa tu propio calor corporal',
          '3. Envuelve en mantas tibias',
          '4. Almohadilla térmica en configuración BAJA',
          '5. Verifica temperatura cada 30 minutos',
          '6. NO alimentes hasta que esté tibio (36°C+)',
          '',
          'Prevención:',
          '• Mantén zona de cría a 29-32°C (primera semana)',
          '• Reduce gradualmente cada semana',
          '• Usa almohadillas térmicas o lámparas',
          '• Evita corrientes de aire',
        ],
      },
      {
        title: 'Deshidratación',
        content: [
          'Los cachorros/gatitos se deshidratan rápidamente:',
          '',
          'Causas comunes:',
          '• Diarrea',
          '• Vómito',
          '• Fiebre',
          '• No estar mamando adecuadamente',
          '',
          'Test de deshidratación (test de piel):',
          '1. Levanta suavemente la piel del cuello',
          '2. Suéltala',
          '3. Debe volver a su posición inmediatamente',
          '• Si tarda en volver: deshidratación moderada',
          '• Si queda elevada: deshidratación severa',
          '',
          'Otros signos:',
          '• Encías secas o pegajosas',
          '• Ojos hundidos',
          '• Letargo',
          '• Orina oscura o muy concentrada',
          '',
          'Tratamiento en casa (deshidratación LEVE):',
          '• Ofrece agua fresca frecuentemente',
          '• Suero oral pediátrico (Pedialyte sin sabor)',
          '• Comidas húmedas',
          '',
          'Busca veterinario si:',
          '• Deshidratación moderada o severa',
          '• No bebe',
          '• Vómito o diarrea continúan',
          '• El cachorro es menor de 8 semanas',
        ],
      },
      {
        title: 'Parásitos y Emergencias Digestivas',
        content: [
          'Los parásitos pueden ser mortales en cachorros:',
          '',
          'Signos de emergencia parasitaria:',
          '• Diarrea con sangre',
          '• Vómito con gusanos',
          '• Abdomen muy distendido',
          '• Anemia severa (encías blancas)',
          '• Debilidad extrema',
          '• Obstrucción intestinal por bola de parásitos',
          '',
          'PARVOVIRUS - EMERGENCIA CRÍTICA:',
          'Altamente contagioso y mortal en cachorros',
          '',
          'Signos:',
          '• Vómito severo',
          '• Diarrea con sangre y olor muy fétido',
          '• Letargo extremo',
          '• Fiebre seguida de hipotermia',
          '• Deshidratación rápida',
          '',
          'Acción:',
          '• Aísla inmediatamente de otros perros',
          '• URGENCIA VETERINARIA INMEDIATA',
          '• Sin tratamiento, mortalidad es del 90%',
          '• Con tratamiento agresivo, puede sobrevivir',
          '',
          'Prevención:',
          '• Vacunación completa',
          '• Evita áreas públicas antes de vacunación',
          '• Desparasitación regular',
        ],
      },
    ],
  },
};

export function GuideDetail({ guideId }: GuideDetailProps) {
  const guide = guideContent[guideId];

  if (!guide) {
    return (
      <div className="min-h-screen bg-gradient-to-b from-emerald-50 to-blue-50 p-6">
        <p>Guía no encontrada</p>
      </div>
    );
  }

  return (
    <div className="min-h-screen bg-gradient-to-b from-emerald-50 to-blue-50 pb-24">
      {/* Header */}
      <div className="bg-gradient-to-br from-emerald-300 to-blue-300 p-6">
        <div className="mb-3 flex items-center gap-2">
          <Badge className="bg-slate-100 text-slate-700 border-slate-300">
            <Clock className="size-3 mr-1" />
            {guide.readTime}
          </Badge>
          {guide.offline && (
            <Badge className="bg-emerald-100 text-emerald-700 border-emerald-300">
              <Download className="size-3 mr-1" />
              Offline
            </Badge>
          )}
        </div>
        <h1 className="text-slate-800 mb-2">{guide.title}</h1>
      </div>

      <div className="px-6 py-6">
        {/* Alerta importante */}
        <Card className="bg-amber-100 border-amber-300 mb-6">
          <div className="p-4 flex gap-3">
            <AlertTriangle className="size-5 text-amber-700 flex-shrink-0 mt-0.5" />
            <div>
              <p className="text-amber-900">
                <strong>Importante:</strong> Esta información es para primeros auxilios básicos.
                En caso de emergencia, siempre busca atención veterinaria profesional lo antes posible.
              </p>
            </div>
          </div>
        </Card>

        {/* Contenido por secciones */}
        <div className="space-y-6">
          {guide.sections.map((section: any, index: number) => (
            <Card key={index} className="bg-white border-slate-200 shadow-sm">
              <div className="p-6">
                <h2 className="text-slate-800 mb-4">{section.title}</h2>
                <div className="space-y-2">
                  {section.content.map((paragraph: string, pIndex: number) => (
                    <p
                      key={pIndex}
                      className={`text-slate-700 leading-relaxed ${
                        paragraph.startsWith('•') ? 'ml-4' : ''
                      } ${paragraph === '' ? 'h-2' : ''} ${
                        paragraph.startsWith('🔴') ||
                        paragraph.includes('IMPORTANTE') ||
                        paragraph.includes('URGENTE') ||
                        paragraph.includes('NUNCA')
                          ? 'font-medium'
                          : ''
                      }`}
                    >
                      {paragraph}
                    </p>
                  ))}
                </div>
              </div>
            </Card>
          ))}
        </div>

        {/* Botón de descarga */}
        {guide.offline && (
          <Button className="w-full h-14 bg-emerald-300 hover:bg-emerald-400 text-emerald-900 mt-6">
            <Download className="size-5 mr-2" />
            Guardar para uso sin conexión
          </Button>
        )}
      </div>
    </div>
  );
}
